//! Decision record type and non-blocking bounded-channel sink.
//!
//! # Decision record schema
//!
//! Every transform outcome — modification or passthrough — produces exactly one
//! [`DecisionRecord`]. Records are structured JSON:
//!
//! ```json
//! {
//!   "request_id": "req-abc-123",
//!   "component": "metadata-reorder",
//!   "decision": "modified",
//!   "bytes_in": 4096,
//!   "bytes_out": 4082
//! }
//! ```
//!
//! The `request_id` is always caller-assigned (invariant 5: no entropy in the
//! transform path — no UUID generation here).
//!
//! # Sink contract
//!
//! [`DecisionSink`] is a trait with a single non-blocking method. The concrete
//! [`ChannelDecisionSink`] wraps a bounded `crossbeam_channel::Sender`.
//!
//! When the channel is at capacity, `try_send` returns `Err(SinkFull)`. The
//! caller (in [`crate::guardrail`]) MUST then emit byte-faithful passthrough
//! rather than an unlogged modification — invariant 8 (logged-never-silent).
//!
//! The method is explicitly NOT `async` — this crate is entirely sync.
//!
//! # Sensitive field redaction
//!
//! Auth material must NEVER appear unredacted in decision records. The scrub
//! lists below are declared in this crate (not imported from the binary crate)
//! so they are available to all consumers without pulling in `rskim`.

use std::sync::Arc;

// ============================================================================
// Sensitive field scrub lists (declared here, not imported from rskim binary)
// ============================================================================

/// Exact key names that must be redacted in decision record values.
///
/// Matches the scrub list in `crates/rskim/src/cmd/file/env.rs::SENSITIVE_EXACT`
/// plus additional L3-relevant keys. Kept in sync manually; the canonical source
/// for binary-facing redaction is the env.rs list.
pub const SENSITIVE_EXACT: &[&str] = &[
    "ANTHROPIC_API_KEY",
    "OPENAI_API_KEY",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "GITHUB_TOKEN",
    "GH_TOKEN",
    "DATABASE_URL",
    "NPM_TOKEN",
    "STRIPE_SECRET_KEY",
    "SENTRY_DSN",
    "SENDGRID_API_KEY",
];

/// Key suffixes that indicate sensitive values (case-insensitive).
///
/// Matches `crates/rskim/src/cmd/file/env.rs::SENSITIVE_SUFFIXES`.
pub const SENSITIVE_SUFFIXES: &[&str] = &[
    "_TOKEN",
    "_SECRET",
    "_PASSWORD",
    "_API_KEY",
    "_SECRET_KEY",
    "_PRIVATE_KEY",
    "_ENCRYPTION_KEY",
    "_SIGNING_KEY",
    "_ACCESS_KEY",
    "_HMAC_KEY",
    "_CREDENTIAL",
    "_AUTH",
];

/// Returns `true` if `key` matches a sensitive key name and its value should
/// be redacted before appearing in any log record.
///
/// # Examples
///
/// ```rust
/// use rskim_contract::log::is_sensitive_key;
/// assert!(is_sensitive_key("ANTHROPIC_API_KEY"));
/// assert!(is_sensitive_key("MY_TOKEN"));
/// assert!(!is_sensitive_key("MODEL_NAME"));
/// ```
pub fn is_sensitive_key(key: &str) -> bool {
    let upper = key.to_uppercase();
    SENSITIVE_EXACT.iter().any(|&e| e == upper)
        || SENSITIVE_SUFFIXES.iter().any(|&s| upper.ends_with(s))
}

// ============================================================================
// DecisionRecord
// ============================================================================

/// The decision variant: whether bytes were modified or passed through.
#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "snake_case")]
#[non_exhaustive]
pub enum Decision {
    /// Output bytes differ from input bytes.
    Modified,
    /// Output bytes equal input bytes (fail-open or no-op).
    Passthrough,
}

/// A structured decision record produced by every L3 transform.
///
/// The record is JSON-serialisable. It is produced for every call to
/// [`crate::contract::Contract::transform`], whether the transform modifies
/// the input or passes it through unchanged.
///
/// # Invariant 8 (logged-never-silent)
///
/// An unlogged modification must not be emitted. If [`DecisionSink::try_send`]
/// returns `Err(SinkFull)`, the transform MUST fall back to passthrough.
/// See [`crate::guardrail::guarded_transform`].
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DecisionRecord {
    /// Caller-assigned request identifier. Never generated by the transform path.
    pub request_id: String,
    /// Stable component name (e.g., `"metadata-reorder"`, `"identity"`).
    pub component: &'static str,
    /// Whether this record represents a modification or passthrough.
    pub decision: Decision,
    /// Input byte count.
    pub bytes_in: usize,
    /// Output byte count.
    pub bytes_out: usize,
}

impl DecisionRecord {
    /// Construct a passthrough record.
    ///
    /// `bytes_in == bytes_out` for passthrough; the invariant is recorded
    /// in both fields for consistency.
    ///
    /// # Caller contract: `request_id` must not contain auth material
    ///
    /// `request_id` is serialized verbatim into the record JSON. AC12 mandates
    /// that auth material MUST NEVER appear unredacted in any log record. Callers
    /// MUST use an opaque, non-secret correlation identifier (e.g., a UUID or a
    /// hashed request identifier), never a bearer token, API key, or value derived
    /// from a request header that could carry auth material.
    ///
    /// A `debug_assert` checks this at construction time in debug builds.
    pub fn passthrough(request_id: &str, component: &'static str, bytes_in: usize) -> Self {
        // Defense-in-depth: assert in debug builds that request_id is not a
        // known sensitive key name. This catches obvious misuse at the trust
        // boundary during development without overhead in release builds.
        debug_assert!(
            !is_sensitive_key(request_id),
            "AC12 violation: request_id '{request_id}' matches a sensitive key pattern — \
             use an opaque correlation identifier, not an auth material value"
        );
        Self {
            request_id: request_id.to_owned(),
            component,
            decision: Decision::Passthrough,
            bytes_in,
            bytes_out: bytes_in,
        }
    }

    /// Construct a modification record.
    ///
    /// # Caller contract: `request_id` must not contain auth material
    ///
    /// See [`DecisionRecord::passthrough`] for the full AC12 caller contract.
    pub fn modified(
        request_id: &str,
        component: &'static str,
        bytes_in: usize,
        bytes_out: usize,
    ) -> Self {
        debug_assert!(
            !is_sensitive_key(request_id),
            "AC12 violation: request_id '{request_id}' matches a sensitive key pattern — \
             use an opaque correlation identifier, not an auth material value"
        );
        Self {
            request_id: request_id.to_owned(),
            component,
            decision: Decision::Modified,
            bytes_in,
            bytes_out,
        }
    }

    /// Returns `true` if this is a passthrough record.
    pub fn is_passthrough(&self) -> bool {
        matches!(self.decision, Decision::Passthrough)
    }

    /// Serialise this record to a compact JSON string.
    ///
    /// Returns `None` if serialisation fails (should never happen in practice
    /// since all fields are primitive types).
    pub fn to_json(&self) -> Option<String> {
        serde_json::to_string(self).ok()
    }
}

// ============================================================================
// DecisionSink trait and SinkFull error
// ============================================================================

/// Error returned when the bounded decision channel is at capacity.
///
/// When `try_send` returns `SinkFull`, the caller MUST emit byte-faithful
/// passthrough (invariant 8 / AC14). A modification whose record was not
/// accepted MUST fail conformance.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[error("decision sink is full — caller must fall back to passthrough")]
pub struct SinkFull;

/// Non-blocking bounded sink for decision records.
///
/// # Contract
///
/// - `try_send` MUST be non-blocking by type (no `async`, no `await`).
/// - On `Err(SinkFull)`, the caller MUST NOT emit a modification.
/// - Implementations MUST be `Send + Sync` (can be cloned and shared across threads).
///
/// # Dependency injection
///
/// The sink is a constructor parameter, not a global. Tests use [`MockSink`];
/// production code uses [`ChannelDecisionSink`]. The #305 sink-persistence
/// consumer provides the persistent database-backed implementation.
pub trait DecisionSink: Send + Sync {
    /// Attempt to send `record` to the sink without blocking.
    ///
    /// Returns `Ok(())` if the record was accepted, `Err(SinkFull)` if the
    /// channel is at capacity. The caller MUST fall back to passthrough on
    /// `Err(SinkFull)`.
    fn try_send(&self, record: DecisionRecord) -> std::result::Result<(), SinkFull>;
}

// ============================================================================
// ChannelDecisionSink — crossbeam-channel backed concrete implementation
// ============================================================================

/// Bounded crossbeam-channel backed [`DecisionSink`].
///
/// Wraps a `crossbeam_channel::Sender<DecisionRecord>` with bounded capacity.
/// `try_send` maps `TrySendError::Full` to `SinkFull` and `TrySendError::Disconnected`
/// to `SinkFull` (fail-open: treat a disconnected receiver as "full" so callers
/// fall back to passthrough, never block).
///
/// # Construction
///
/// ```rust
/// use rskim_contract::log::{ChannelDecisionSink, DecisionRecord};
///
/// let (sink, receiver) = ChannelDecisionSink::new(128);
/// // Hand `sink` to a Contract impl; consume from `receiver` on a drain thread.
/// ```
///
/// # Thread safety
///
/// `ChannelDecisionSink` is `Clone`, `Send`, and `Sync`. Multiple components can
/// share the same sink by cloning it.
#[derive(Clone)]
pub struct ChannelDecisionSink {
    sender: crossbeam_channel::Sender<DecisionRecord>,
}

impl ChannelDecisionSink {
    /// Create a new sink with the given channel capacity.
    ///
    /// Returns `(sink, receiver)`. Pass `sink` to transform components;
    /// drain `receiver` on a background thread to avoid blocking the transform
    /// path when the channel approaches capacity.
    ///
    /// # Panics
    ///
    /// Never panics. `crossbeam_channel::bounded` accepts any capacity ≥ 0.
    pub fn new(capacity: usize) -> (Self, crossbeam_channel::Receiver<DecisionRecord>) {
        let (sender, receiver) = crossbeam_channel::bounded(capacity);
        (Self { sender }, receiver)
    }
}

impl DecisionSink for ChannelDecisionSink {
    fn try_send(&self, record: DecisionRecord) -> std::result::Result<(), SinkFull> {
        // Both Full and Disconnected map to SinkFull: callers fall back to passthrough.
        self.sender.try_send(record).map_err(|_| SinkFull)
    }
}

// ============================================================================
// MockSink — in-memory test double
// ============================================================================

/// In-memory decision sink for tests.
///
/// Captures all records sent to it so tests can assert the exact record
/// content without a real channel. Thread-safe via `std::sync::Mutex`.
///
/// ```rust
/// use rskim_contract::log::{MockSink, DecisionSink, DecisionRecord};
/// use std::sync::Arc;
///
/// let sink = Arc::new(MockSink::new());
/// let record = DecisionRecord::passthrough("req-1", "test", 42);
/// sink.try_send(record).unwrap();
/// let records = sink.drain();
/// assert_eq!(records.len(), 1);
/// assert_eq!(records[0].request_id, "req-1");
/// ```
pub struct MockSink {
    records: std::sync::Mutex<Vec<DecisionRecord>>,
    /// When `true`, `try_send` always returns `Err(SinkFull)`.
    full: std::sync::atomic::AtomicBool,
}

impl MockSink {
    /// Create a new empty mock sink.
    pub fn new() -> Self {
        Self {
            records: std::sync::Mutex::new(Vec::new()),
            full: std::sync::atomic::AtomicBool::new(false),
        }
    }

    /// Configure the sink to simulate a full channel for the next calls.
    pub fn set_full(&self, full: bool) {
        self.full.store(full, std::sync::atomic::Ordering::Relaxed);
    }

    /// Drain and return all captured records, leaving the sink empty.
    ///
    /// # Panics
    ///
    /// Panics if the internal mutex is poisoned (only happens when a thread
    /// panicked while holding the lock — acceptable in test code).
    pub fn drain(&self) -> Vec<DecisionRecord> {
        std::mem::take(&mut *self.lock())
    }

    /// Return the number of records currently held.
    pub fn len(&self) -> usize {
        self.lock().len()
    }

    /// Returns `true` if no records have been captured.
    pub fn is_empty(&self) -> bool {
        self.lock().is_empty()
    }

    fn lock(&self) -> std::sync::MutexGuard<'_, Vec<DecisionRecord>> {
        self.records.lock().unwrap_or_else(|e| e.into_inner())
    }
}

impl Default for MockSink {
    fn default() -> Self {
        Self::new()
    }
}

impl DecisionSink for MockSink {
    fn try_send(&self, record: DecisionRecord) -> std::result::Result<(), SinkFull> {
        if self.full.load(std::sync::atomic::Ordering::Relaxed) {
            return Err(SinkFull);
        }
        self.lock().push(record);
        Ok(())
    }
}

// Allow Arc<MockSink> to be used as a DecisionSink.
impl<T: DecisionSink> DecisionSink for Arc<T> {
    fn try_send(&self, record: DecisionRecord) -> std::result::Result<(), SinkFull> {
        (**self).try_send(record)
    }
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn is_sensitive_key_exact_match() {
        assert!(is_sensitive_key("ANTHROPIC_API_KEY"));
        assert!(is_sensitive_key("OPENAI_API_KEY"));
        assert!(is_sensitive_key("GITHUB_TOKEN"));
    }

    #[test]
    fn is_sensitive_key_suffix_match() {
        assert!(is_sensitive_key("MY_SERVICE_TOKEN"));
        assert!(is_sensitive_key("DB_PASSWORD"));
        assert!(is_sensitive_key("SERVICE_API_KEY"));
    }

    #[test]
    fn is_sensitive_key_non_sensitive() {
        assert!(!is_sensitive_key("MODEL_NAME"));
        assert!(!is_sensitive_key("REQUEST_ID"));
        assert!(!is_sensitive_key("COMPONENT"));
        assert!(!is_sensitive_key("SORT_KEY")); // _KEY alone is not sensitive
    }

    #[test]
    fn is_sensitive_key_case_insensitive() {
        assert!(is_sensitive_key("anthropic_api_key"));
        assert!(is_sensitive_key("my_service_token"));
    }

    #[test]
    fn decision_record_passthrough_fields() {
        let r = DecisionRecord::passthrough("req-1", "identity", 100);
        assert_eq!(r.request_id, "req-1");
        assert_eq!(r.component, "identity");
        assert!(r.is_passthrough());
        assert_eq!(r.bytes_in, 100);
        assert_eq!(r.bytes_out, 100);
    }

    #[test]
    fn decision_record_modified_fields() {
        let r = DecisionRecord::modified("req-2", "compressor", 200, 150);
        assert_eq!(r.bytes_in, 200);
        assert_eq!(r.bytes_out, 150);
        assert!(!r.is_passthrough());
    }

    #[test]
    fn decision_record_to_json_round_trips() {
        let r = DecisionRecord::passthrough("req-3", "test", 42);
        let json = r.to_json().expect("serialisation must succeed");
        let parsed: serde_json::Value =
            serde_json::from_str(&json).expect("must produce valid JSON");
        assert_eq!(parsed["request_id"], "req-3");
        assert_eq!(parsed["component"], "test");
        assert_eq!(parsed["decision"], "passthrough");
        assert_eq!(parsed["bytes_in"], 42);
        assert_eq!(parsed["bytes_out"], 42);
    }

    #[test]
    fn channel_sink_accepts_records() {
        let (sink, rx) = ChannelDecisionSink::new(16);
        let r = DecisionRecord::passthrough("r1", "c", 10);
        sink.try_send(r).expect("channel has capacity");
        let received = rx.try_recv().expect("record must be present");
        assert_eq!(received.request_id, "r1");
    }

    #[test]
    fn channel_sink_full_returns_sink_full() {
        let (sink, _rx) = ChannelDecisionSink::new(1);
        let r1 = DecisionRecord::passthrough("r1", "c", 1);
        sink.try_send(r1).expect("first send must succeed");
        let r2 = DecisionRecord::passthrough("r2", "c", 2);
        let err = sink.try_send(r2).expect_err("channel must be full");
        assert_eq!(err, SinkFull);
    }

    #[test]
    fn channel_sink_disconnected_returns_sink_full() {
        // Drop the receiver so the sender is disconnected.
        let (sender, _receiver) = crossbeam_channel::bounded::<DecisionRecord>(1);
        drop(_receiver);
        let sink = ChannelDecisionSink { sender };
        let r = DecisionRecord::passthrough("r1", "c", 10);
        let err = sink
            .try_send(r)
            .expect_err("disconnected must look like Full");
        assert_eq!(err, SinkFull);
    }

    #[test]
    fn channel_sink_is_clone_send_sync() {
        fn assert_send_sync_clone<T: Send + Sync + Clone>() {}
        assert_send_sync_clone::<ChannelDecisionSink>();
    }

    #[test]
    fn mock_sink_captures_records() {
        let sink = MockSink::new();
        sink.try_send(DecisionRecord::passthrough("r1", "c", 1))
            .unwrap();
        sink.try_send(DecisionRecord::modified("r2", "c", 10, 8))
            .unwrap();
        let records = sink.drain();
        assert_eq!(records.len(), 2);
        assert_eq!(records[0].request_id, "r1");
        assert_eq!(records[1].request_id, "r2");
        assert!(sink.is_empty());
    }

    #[test]
    fn mock_sink_full_simulation() {
        let sink = MockSink::new();
        sink.set_full(true);
        let err = sink
            .try_send(DecisionRecord::passthrough("r1", "c", 1))
            .expect_err("must return SinkFull when set_full=true");
        assert_eq!(err, SinkFull);
        sink.set_full(false);
        sink.try_send(DecisionRecord::passthrough("r2", "c", 1))
            .expect("must accept after set_full=false");
        assert_eq!(sink.len(), 1);
    }

    #[test]
    fn arc_mock_sink_impl() {
        let sink = Arc::new(MockSink::new());
        sink.try_send(DecisionRecord::passthrough("r1", "c", 5))
            .unwrap();
        assert_eq!(sink.len(), 1);
    }
}
