//! Code generation for AST weight tables.
//!
//! Reads an `AstWeightTable` from JSON and generates a compilable `ast_weights.rs`
//! for `rskim-search`, containing per-language bigram and trigram weight arrays
//! with binary-search lookup functions.

use std::io::Write;
use std::path::Path;

use anyhow::Context;

use crate::ast_types::AstWeightTable;
use crate::codegen::find_workspace_root;

/// Read `json_path`, validate the AST weight table, and write a compilable
/// `ast_weights.rs` to `output_path`.
///
/// The generated file contains:
/// - `NODE_KIND_VOCABULARY: &[&str]` — all node kind strings indexed by ID.
/// - Per-language `{LANG}_AST_BIGRAM_WEIGHTS: &[(u32, f32)]` sorted ascending.
/// - Per-language `{LANG}_AST_TRIGRAM_WEIGHTS: &[(u64, f32)]` sorted ascending.
/// - `pub fn ast_bigram_weight(lang: &str, bigram: u32) -> Option<f32>`
/// - `pub fn ast_trigram_weight(lang: &str, trigram: u64) -> Option<f32>`
///
/// # Errors
///
/// Returns an error if:
/// - `json_path` cannot be read or parsed as `AstWeightTable`
/// - The weight table version is 0
/// - Any IDF value is non-positive or non-finite
/// - Writing to `output_path` fails
pub fn generate_ast_weights_rs(json_path: &Path, output_path: &Path) -> anyhow::Result<()> {
    let raw = std::fs::read_to_string(json_path)
        .with_context(|| format!("reading {}", json_path.display()))?;

    let table: AstWeightTable = serde_json::from_str(&raw)
        .with_context(|| format!("parsing AST weight table from {}", json_path.display()))?;

    validate_ast_table(&table)?;

    let source = build_ast_weights_rs(&table)?;

    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating directory {}", parent.display()))?;
    }

    std::fs::write(output_path, source)
        .with_context(|| format!("writing {}", output_path.display()))?;

    Ok(())
}

/// Validate the AST weight table contents.
fn validate_ast_table(table: &AstWeightTable) -> anyhow::Result<()> {
    if table.version == 0 {
        anyhow::bail!("AST weight table version must be > 0");
    }
    if table.vocabulary.is_empty() {
        anyhow::bail!("AST weight table vocabulary is empty");
    }

    for (lang, bigrams) in &table.bigram_weights {
        for w in bigrams {
            if !w.idf.is_finite() || w.idf <= 0.0 {
                anyhow::bail!(
                    "invalid IDF {:.6} for bigram 0x{:08X} in language '{}' — all IDF values must be finite and positive",
                    w.idf,
                    w.bigram,
                    lang
                );
            }
        }
    }

    for (lang, trigrams) in &table.trigram_weights {
        for w in trigrams {
            if !w.idf.is_finite() || w.idf <= 0.0 {
                anyhow::bail!(
                    "invalid IDF {:.6} for trigram 0x{:016X} in language '{}' — all IDF values must be finite and positive",
                    w.idf,
                    w.trigram,
                    lang
                );
            }
        }
    }

    Ok(())
}

/// Build the Rust source string for `ast_weights.rs`.
fn build_ast_weights_rs(table: &AstWeightTable) -> anyhow::Result<String> {
    let mut buf: Vec<u8> = Vec::with_capacity(256 * 1024);
    write_ast_file_header(&mut buf, table)?;
    write_vocabulary(&mut buf, &table.vocabulary)?;
    write_language_bigram_arrays(&mut buf, table)?;
    write_language_trigram_arrays(&mut buf, table)?;
    write_bigram_lookup_fn(&mut buf, table)?;
    write_trigram_lookup_fn(&mut buf, table)?;
    write_ast_generated_tests(&mut buf)?;
    String::from_utf8(buf).context("building ast_weights.rs source (non-UTF8 output)")
}

fn write_ast_file_header(buf: &mut Vec<u8>, table: &AstWeightTable) -> anyhow::Result<()> {
    writeln!(buf, "//! Auto-generated by rskim-research ast-codegen.")?;
    writeln!(buf, "//!")?;
    writeln!(
        buf,
        "//! Version: {}  |  Generated: {}",
        table.version, table.generated_at
    )?;
    writeln!(
        buf,
        "//! Vocabulary: {} node kinds  |  Languages: {}",
        table.vocabulary.len(),
        table.bigram_weights.len()
    )?;
    writeln!(buf, "//!")?;
    writeln!(
        buf,
        "//! DO NOT EDIT MANUALLY — re-run `rskim-research ast-codegen` to regenerate."
    )?;
    writeln!(buf)?;
    writeln!(buf, "#![allow(clippy::excessive_precision)]")?;
    writeln!(buf)?;
    Ok(())
}

fn write_vocabulary(buf: &mut Vec<u8>, vocabulary: &[String]) -> anyhow::Result<()> {
    writeln!(buf, "/// All node kind strings, indexed by `NodeKindId`.")?;
    writeln!(buf, "///")?;
    writeln!(
        buf,
        "/// `NODE_KIND_VOCABULARY[id]` resolves a compact ID to its kind string."
    )?;
    writeln!(buf, "pub const NODE_KIND_VOCABULARY: &[&str] = &[")?;
    for kind in vocabulary {
        writeln!(buf, "    {:?},", kind)?;
    }
    writeln!(buf, "];")?;
    writeln!(buf)?;
    Ok(())
}

/// Produce a stable Rust identifier fragment from a language name.
///
/// Examples: `"Rust"` → `"RUST"`, `"TypeScript"` → `"TYPESCRIPT"`,
/// `"C++"` → `"CPP"`, `"C#"` → `"CSHARP"`.
fn lang_to_ident(lang: &str) -> String {
    lang.chars()
        .map(|c| match c {
            '+' => '_',
            '#' => '_',
            '-' => '_',
            ' ' => '_',
            _ => c.to_ascii_uppercase(),
        })
        .collect::<String>()
        // Collapse any repeated underscores introduced by the mapping above.
        .split("__")
        .collect::<Vec<_>>()
        .join("_")
}

fn write_language_bigram_arrays(buf: &mut Vec<u8>, table: &AstWeightTable) -> anyhow::Result<()> {
    let mut sorted_langs: Vec<&String> = table.bigram_weights.keys().collect();
    sorted_langs.sort();

    for lang in sorted_langs {
        let weights = &table.bigram_weights[lang];
        let ident = lang_to_ident(lang);

        // Sort by bigram key ascending for binary search.
        let mut sorted: Vec<_> = weights.iter().collect();
        sorted.sort_by_key(|w| w.bigram);

        writeln!(
            buf,
            "/// {lang} AST bigram weights — sorted ascending by bigram key for O(log n) lookup."
        )?;
        writeln!(
            buf,
            "pub const {ident}_AST_BIGRAM_WEIGHTS: &[(u32, f32)] = &["
        )?;
        for w in &sorted {
            writeln!(
                buf,
                "    (0x{:08X}, {:.6}_f32), // {} -> {}",
                w.bigram, w.idf, w.parent_kind, w.child_kind
            )?;
        }
        writeln!(buf, "];")?;
        writeln!(buf)?;
    }

    Ok(())
}

fn write_language_trigram_arrays(buf: &mut Vec<u8>, table: &AstWeightTable) -> anyhow::Result<()> {
    let mut sorted_langs: Vec<&String> = table.trigram_weights.keys().collect();
    sorted_langs.sort();

    for lang in sorted_langs {
        let weights = &table.trigram_weights[lang];
        let ident = lang_to_ident(lang);

        // Sort by trigram key ascending for binary search.
        let mut sorted: Vec<_> = weights.iter().collect();
        sorted.sort_by_key(|w| w.trigram);

        writeln!(
            buf,
            "/// {lang} AST trigram weights — sorted ascending by trigram key for O(log n) lookup."
        )?;
        writeln!(
            buf,
            "pub const {ident}_AST_TRIGRAM_WEIGHTS: &[(u64, f32)] = &["
        )?;
        for w in &sorted {
            writeln!(
                buf,
                "    (0x{:016X}, {:.6}_f32), // {} -> {} -> {}",
                w.trigram, w.idf, w.grandparent_kind, w.parent_kind, w.child_kind
            )?;
        }
        writeln!(buf, "];")?;
        writeln!(buf)?;
    }

    Ok(())
}

fn write_bigram_lookup_fn(buf: &mut Vec<u8>, table: &AstWeightTable) -> anyhow::Result<()> {
    writeln!(
        buf,
        "/// Look up the IDF weight of an AST bigram for a given language."
    )?;
    writeln!(buf, "///")?;
    writeln!(
        buf,
        "/// Returns `None` if the language or bigram is not in the table."
    )?;
    writeln!(buf, "#[must_use]")?;
    writeln!(
        buf,
        "pub fn ast_bigram_weight(lang: &str, bigram: u32) -> Option<f32> {{"
    )?;
    writeln!(buf, "    let table: &[(u32, f32)] = match lang {{")?;

    let mut sorted_langs: Vec<&String> = table.bigram_weights.keys().collect();
    sorted_langs.sort();
    for lang in sorted_langs {
        let ident = lang_to_ident(lang);
        writeln!(buf, "        {:?} => {ident}_AST_BIGRAM_WEIGHTS,", lang)?;
    }
    writeln!(buf, "        _ => return None,")?;
    writeln!(buf, "    }};")?;
    writeln!(buf, "    table")?;
    writeln!(buf, "        .binary_search_by_key(&bigram, |&(k, _)| k)")?;
    writeln!(buf, "        .ok()")?;
    writeln!(buf, "        .map(|idx| table[idx].1)")?;
    writeln!(buf, "}}")?;
    writeln!(buf)?;
    Ok(())
}

fn write_trigram_lookup_fn(buf: &mut Vec<u8>, table: &AstWeightTable) -> anyhow::Result<()> {
    writeln!(
        buf,
        "/// Look up the IDF weight of an AST trigram for a given language."
    )?;
    writeln!(buf, "///")?;
    writeln!(
        buf,
        "/// Returns `None` if the language or trigram is not in the table."
    )?;
    writeln!(buf, "#[must_use]")?;
    writeln!(
        buf,
        "pub fn ast_trigram_weight(lang: &str, trigram: u64) -> Option<f32> {{"
    )?;
    writeln!(buf, "    let table: &[(u64, f32)] = match lang {{")?;

    let mut sorted_langs: Vec<&String> = table.trigram_weights.keys().collect();
    sorted_langs.sort();
    for lang in sorted_langs {
        let ident = lang_to_ident(lang);
        writeln!(buf, "        {:?} => {ident}_AST_TRIGRAM_WEIGHTS,", lang)?;
    }
    writeln!(buf, "        _ => return None,")?;
    writeln!(buf, "    }};")?;
    writeln!(buf, "    table")?;
    writeln!(buf, "        .binary_search_by_key(&trigram, |&(k, _)| k)")?;
    writeln!(buf, "        .ok()")?;
    writeln!(buf, "        .map(|idx| table[idx].1)")?;
    writeln!(buf, "}}")?;
    writeln!(buf)?;
    Ok(())
}

fn write_ast_generated_tests(buf: &mut Vec<u8>) -> anyhow::Result<()> {
    writeln!(buf, "#[cfg(test)]")?;
    writeln!(buf, "mod tests {{")?;
    writeln!(buf, "    use super::*;")?;
    writeln!(buf)?;
    writeln!(buf, "    #[test]")?;
    writeln!(buf, "    fn vocabulary_is_non_empty() {{")?;
    writeln!(
        buf,
        "        assert!(!NODE_KIND_VOCABULARY.is_empty(), \"vocabulary must not be empty\");"
    )?;
    writeln!(buf, "    }}")?;
    writeln!(buf, "}}")?;
    Ok(())
}

/// Default output path for `ast_weights.rs` within the workspace.
pub fn default_ast_weights_output_path() -> anyhow::Result<std::path::PathBuf> {
    let root = find_workspace_root()?;
    Ok(root.join("crates/rskim-search/src/ast_weights.rs"))
}

/// Default input path for `ast_weights.json` within the workspace.
pub fn default_ast_weights_json_path() -> anyhow::Result<std::path::PathBuf> {
    let root = find_workspace_root()?;
    Ok(root.join("crates/rskim-search/data/ast_weights.json"))
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use std::collections::HashMap;

    use super::*;
    use crate::ast_types::{
        AstBigramWeight, AstCorpusStats, AstLanguageStats, AstTrigramWeight, AstWeightTable,
        encode_ast_bigram, encode_ast_trigram,
    };

    fn sample_table() -> AstWeightTable {
        let mut bigram_weights = HashMap::new();
        bigram_weights.insert(
            "Rust".to_string(),
            vec![
                AstBigramWeight {
                    parent_kind: "source_file".to_string(),
                    child_kind: "function_item".to_string(),
                    bigram: encode_ast_bigram(1, 0),
                    idf: 3.5,
                },
                AstBigramWeight {
                    parent_kind: "function_item".to_string(),
                    child_kind: "identifier".to_string(),
                    bigram: encode_ast_bigram(0, 1),
                    idf: 2.5,
                },
            ],
        );

        let mut trigram_weights = HashMap::new();
        trigram_weights.insert(
            "Rust".to_string(),
            vec![AstTrigramWeight {
                grandparent_kind: "source_file".to_string(),
                parent_kind: "function_item".to_string(),
                child_kind: "identifier".to_string(),
                trigram: encode_ast_trigram(2, 1, 0),
                idf: 4.0,
            }],
        );

        AstWeightTable {
            version: 1,
            generated_at: "unix:0".to_string(),
            vocabulary: vec![
                "function_item".to_string(),
                "identifier".to_string(),
                "source_file".to_string(),
            ],
            corpus_stats: AstCorpusStats {
                total_files: 10,
                deduplicated_files: 0,
                language_stats: vec![AstLanguageStats {
                    language: "Rust".to_string(),
                    file_count: 10,
                    unique_bigrams: 2,
                    unique_trigrams: 1,
                    error_node_count: 0,
                    total_node_count: 100,
                }],
            },
            bigram_weights,
            trigram_weights,
        }
    }

    #[test]
    fn generated_source_contains_vocabulary() {
        let table = sample_table();
        let source = build_ast_weights_rs(&table).unwrap();
        assert!(source.contains("NODE_KIND_VOCABULARY"));
        assert!(source.contains("function_item"));
        assert!(source.contains("identifier"));
    }

    #[test]
    fn generated_source_contains_language_arrays() {
        let table = sample_table();
        let source = build_ast_weights_rs(&table).unwrap();
        assert!(source.contains("RUST_AST_BIGRAM_WEIGHTS"));
        assert!(source.contains("RUST_AST_TRIGRAM_WEIGHTS"));
    }

    #[test]
    fn generated_source_contains_lookup_functions() {
        let table = sample_table();
        let source = build_ast_weights_rs(&table).unwrap();
        assert!(source.contains("pub fn ast_bigram_weight"));
        assert!(source.contains("pub fn ast_trigram_weight"));
    }

    #[test]
    fn bigram_arrays_are_sorted_ascending() {
        let table = sample_table();
        let source = build_ast_weights_rs(&table).unwrap();
        // The first bigram in the sorted array should be the one with the smaller key.
        let key_a = encode_ast_bigram(0, 1); // smaller
        let key_b = encode_ast_bigram(1, 0); // larger
        let pos_a = source.find(&format!("0x{:08X}", key_a)).unwrap();
        let pos_b = source.find(&format!("0x{:08X}", key_b)).unwrap();
        assert!(
            pos_a < pos_b,
            "smaller key (0x{key_a:08X}) should appear before larger key (0x{key_b:08X})"
        );
    }

    #[test]
    fn lang_to_ident_handles_special_chars() {
        assert_eq!(lang_to_ident("Rust"), "RUST");
        assert_eq!(lang_to_ident("TypeScript"), "TYPESCRIPT");
        assert_eq!(lang_to_ident("C++"), "C_");
        assert_eq!(lang_to_ident("C#"), "C_");
        assert_eq!(lang_to_ident("C"), "C");
    }

    #[test]
    fn version_zero_returns_error() {
        let dir = tempfile::tempdir().unwrap();
        let json_path = dir.path().join("ast_weights.json");
        let out_path = dir.path().join("ast_weights.rs");

        let mut table = sample_table();
        table.version = 0;

        let json = serde_json::to_string(&table).unwrap();
        std::fs::write(&json_path, json).unwrap();

        let err = generate_ast_weights_rs(&json_path, &out_path).unwrap_err();
        assert!(err.to_string().contains("version must be > 0"));
    }

    #[test]
    fn negative_idf_returns_error() {
        let dir = tempfile::tempdir().unwrap();
        let json_path = dir.path().join("ast_weights.json");
        let out_path = dir.path().join("ast_weights.rs");

        let mut table = sample_table();
        table.bigram_weights.get_mut("Rust").unwrap()[0].idf = -1.0;

        let json = serde_json::to_string(&table).unwrap();
        std::fs::write(&json_path, json).unwrap();

        let err = generate_ast_weights_rs(&json_path, &out_path).unwrap_err();
        assert!(err.to_string().contains("invalid IDF"));
    }
}
