//! Code generation — produce `weights.rs` for `rskim-search` from the trigram JSON weight table.
//!
//! This module generates a replacement for the legacy `BIGRAM_WEIGHTS` table with
//! a new `TRIGRAM_WEIGHTS: &[(u32, f32)]` constant whose keys are genuine 3-byte
//! trigram keys `(b1 << 16) | (b2 << 8) | b3`.
//!
//! # AD-355-5 / PF-004
//!
//! Keys are `u32` to match the widened [`rskim_search::ngram::Ngram`] type.
//! All byte-to-key shifts must be performed on `u32`-widened values in the
//! rskim-search consumer — this codegen emits literal `u32` constants so no
//! widening is needed at lookup time.

use std::io::Write;
use std::path::{Path, PathBuf};

use anyhow::Context;

use crate::extract::trigram_to_display;
use crate::types::TrigramWeightTable;

/// Default path for `trigram_weights.json`: `<workspace>/crates/rskim-search/data/trigram_weights.json`.
pub fn default_trigram_weights_json_path() -> anyhow::Result<PathBuf> {
    crate::codegen::find_workspace_root()
        .map(|root| root.join("crates/rskim-search/data/trigram_weights.json"))
}

/// Read `json_path`, validate the trigram weight table, and write a compilable
/// `weights.rs` to `output_path`.
///
/// # Errors
///
/// Returns an error if:
/// - `json_path` cannot be read or parsed
/// - The weight table is empty or version is 0
/// - Any IDF value is non-positive or non-finite
/// - Writing to `output_path` fails
///
/// Note: keys with b1 == 0 (NUL-leading trigrams from binary-adjacent source)
/// are **not** rejected — the validation deliberately allows them because such
/// bytes are valid in the trigram key space and the corpus may include files with
/// NUL-prefixed byte sequences.  Only the original bigram keyspace (keys < 0x010000)
/// was logically incompatible, but the v3 reader never interprets any key as a
/// bigram — v2 indexes are rejected wholesale via `FORMAT_VERSION` — so the old
/// rejection of b1 == 0 keys is a documentation artefact, not an enforced constraint.
pub fn generate_weights_rs(json_path: &Path, output_path: &Path) -> anyhow::Result<()> {
    let raw = std::fs::read_to_string(json_path)
        .with_context(|| format!("reading {}", json_path.display()))?;

    let table: TrigramWeightTable = serde_json::from_str(&raw)
        .with_context(|| format!("parsing trigram weight table from {}", json_path.display()))?;

    // Validate table contents.
    if table.version == 0 {
        anyhow::bail!("trigram weight table version must be > 0");
    }
    if table.weights.is_empty() {
        anyhow::bail!("trigram weight table is empty");
    }
    for w in &table.weights {
        if !w.idf.is_finite() || w.idf <= 0.0 {
            anyhow::bail!(
                "invalid IDF {} for trigram 0x{:06X} — all IDF values must be finite and positive",
                w.idf,
                w.trigram
            );
        }
        // Every genuine trigram key must have b1 != 0 when extracted from a real text
        // corpus (the 3-byte key space starts at 0x010000 for b1=0x01).
        // Keys == 0x00_??_?? come from text bytes starting with 0x00 (null bytes),
        // which are valid but rare in source code.  We do NOT enforce b1 > 0 here
        // because the corpus may include binary-adjacent source with null bytes.
    }

    // Generate the Rust source.
    let source = build_weights_rs(&table)?;

    // Create output directory if needed.
    if let Some(parent) = output_path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating directory {}", parent.display()))?;
    }

    std::fs::write(output_path, source)
        .with_context(|| format!("writing {}", output_path.display()))?;

    Ok(())
}

fn build_weights_rs(table: &TrigramWeightTable) -> anyhow::Result<String> {
    let mut buf: Vec<u8> = Vec::with_capacity(256 * 1024);
    write_file_header(&mut buf, table)?;
    write_entries(&mut buf, &table.weights)?;
    write_lookup_fns(&mut buf)?;
    write_generated_tests(&mut buf)?;
    String::from_utf8(buf).context("building weights.rs source (non-UTF8 output)")
}

fn write_file_header(buf: &mut Vec<u8>, table: &TrigramWeightTable) -> anyhow::Result<()> {
    writeln!(
        buf,
        "//! Empirical character trigram IDF weight table for rskim-search sparse index."
    )?;
    writeln!(
        buf,
        "//! Generated by rskim-research trigram-codegen from data/trigram_weights.json"
    )?;
    writeln!(buf, "//!")?;
    writeln!(
        buf,
        "//! Version: {}  |  Generated: {}",
        table.version, table.generated_at
    )?;
    writeln!(
        buf,
        "//! Corpus: {} files, {} unique trigrams",
        table.corpus_stats.total_files, table.corpus_stats.unique_ngrams
    )?;
    writeln!(buf, "//!")?;
    writeln!(
        buf,
        "//! DO NOT EDIT MANUALLY — re-run `rskim-research trigram-run` + `trigram-codegen` to regenerate."
    )?;
    writeln!(buf, "//!")?;
    writeln!(buf, "//! # AD-355-5 / PF-004")?;
    writeln!(buf, "//!")?;
    writeln!(
        buf,
        "//! Keys are `u32` trigrams: `(b1 << 16) | (b2 << 8) | b3`."
    )?;
    writeln!(
        buf,
        "//! All genuine trigram keys are >= 0x010000 when b1 >= 0x01."
    )?;
    writeln!(
        buf,
        "//! Old bigram keys (<= 0xFFFF) will not match any entry in this table."
    )?;
    writeln!(buf, "//!")?;
    writeln!(
        buf,
        "//! #358 will own the v3→v4 format bump for posting compression."
    )?;
    writeln!(buf)?;
    // Suppress excessive_precision lint — the exact float representation is intentional
    // in machine-generated const data.
    writeln!(buf, "#![allow(clippy::excessive_precision)]")?;
    writeln!(buf)?;
    Ok(())
}

fn write_entries(buf: &mut Vec<u8>, weights: &[crate::types::TrigramWeight]) -> anyhow::Result<()> {
    writeln!(buf, "/// Sorted (trigram_key, idf_weight) pairs.")?;
    writeln!(buf, "///")?;
    writeln!(
        buf,
        "/// The table is sorted ascending by trigram key, enabling O(log n) binary search."
    )?;
    writeln!(
        buf,
        "/// Each trigram key encodes three bytes: `key = (b1 << 16) | (b2 << 8) | b3`."
    )?;
    writeln!(buf, "///")?;
    writeln!(buf, "/// # AD-355-5 / PF-004")?;
    writeln!(buf, "///")?;
    writeln!(
        buf,
        "/// Keys widened from `u16` (bigram) to `u32` (trigram) for IDF selectivity (#355 Part B)."
    )?;
    writeln!(
        buf,
        "/// Existing bigram entries are replaced with corpus-derived trigram IDF values."
    )?;
    writeln!(
        buf,
        "/// A larger corpus-derived trigram weight table is planned for #358 (v3→v4)."
    )?;
    writeln!(buf, "pub const TRIGRAM_WEIGHTS: &[(u32, f32)] = &[")?;
    for w in weights {
        let display = trigram_to_display(w.trigram);
        writeln!(
            buf,
            "    (0x{:06X}, {:.6}_f32), // {:?}",
            w.trigram, w.idf, display
        )?;
    }
    writeln!(buf, "];")?;
    writeln!(buf)?;
    writeln!(buf, "/// Default weight for n-grams not in the table.")?;
    writeln!(buf, "pub const DEFAULT_WEIGHT: f32 = 1.0;")?;
    writeln!(buf)?;
    Ok(())
}

fn write_lookup_fns(buf: &mut Vec<u8>) -> anyhow::Result<()> {
    writeln!(
        buf,
        "/// Look up the IDF weight for `key` in any sorted `(key, weight)` slice."
    )?;
    writeln!(buf, "///")?;
    writeln!(
        buf,
        "/// Falls back to [`DEFAULT_WEIGHT`] when `key` is absent from the table."
    )?;
    writeln!(
        buf,
        "/// The caller must ensure the slice is sorted ascending by key."
    )?;
    writeln!(buf, "///")?;
    writeln!(buf, "/// # AD-355-5 / PF-004")?;
    writeln!(buf, "///")?;
    writeln!(
        buf,
        "/// Key is `u32` (was `u16` before #355 Part B) to match the widened"
    )?;
    writeln!(buf, "/// [`crate::ngram::Ngram`] key type.")?;
    writeln!(buf, "#[must_use]")?;
    writeln!(buf, "#[inline]")?;
    writeln!(
        buf,
        "pub fn lookup_weight(key: u32, weights: &[(u32, f32)]) -> f32 {{"
    )?;
    writeln!(buf, "    weights")?;
    writeln!(buf, "        .binary_search_by_key(&key, |&(k, _)| k)")?;
    writeln!(buf, "        .ok()")?;
    writeln!(buf, "        .map(|idx| weights[idx].1)")?;
    writeln!(buf, "        .unwrap_or(DEFAULT_WEIGHT)")?;
    writeln!(buf, "}}")?;
    writeln!(buf)?;
    writeln!(
        buf,
        "/// Look up the IDF weight of an n-gram by binary search against [`TRIGRAM_WEIGHTS`]."
    )?;
    writeln!(buf, "///")?;
    writeln!(
        buf,
        "/// Returns `None` if the n-gram key is absent from the table."
    )?;
    writeln!(buf, "#[must_use]")?;
    writeln!(buf, "pub fn trigram_weight(key: u32) -> Option<f32> {{")?;
    writeln!(buf, "    TRIGRAM_WEIGHTS")?;
    writeln!(buf, "        .binary_search_by_key(&key, |&(k, _)| k)")?;
    writeln!(buf, "        .ok()")?;
    writeln!(buf, "        .map(|idx| TRIGRAM_WEIGHTS[idx].1)")?;
    writeln!(buf, "}}")?;
    writeln!(buf)?;
    Ok(())
}

fn write_generated_tests(buf: &mut Vec<u8>) -> anyhow::Result<()> {
    writeln!(buf, "#[cfg(test)]")?;
    writeln!(buf, "mod tests {{")?;
    writeln!(buf, "    use super::*;")?;
    writeln!(buf)?;
    writeln!(buf, "    #[test]")?;
    writeln!(buf, "    fn table_is_sorted_ascending() {{")?;
    writeln!(
        buf,
        "        let keys: Vec<u32> = TRIGRAM_WEIGHTS.iter().map(|&(k, _)| k).collect();"
    )?;
    writeln!(buf, "        let mut sorted = keys.clone();")?;
    writeln!(buf, "        sorted.sort();")?;
    writeln!(
        buf,
        "        assert_eq!(keys, sorted, \"TRIGRAM_WEIGHTS must be sorted ascending\");"
    )?;
    writeln!(buf, "    }}")?;
    writeln!(buf)?;
    writeln!(buf, "    #[test]")?;
    writeln!(buf, "    fn no_duplicate_keys() {{")?;
    writeln!(buf, "        assert!(")?;
    writeln!(
        buf,
        "            TRIGRAM_WEIGHTS.windows(2).all(|w| w[0].0 != w[1].0),"
    )?;
    writeln!(
        buf,
        "            \"TRIGRAM_WEIGHTS must not have duplicate keys\""
    )?;
    writeln!(buf, "        );")?;
    writeln!(buf, "    }}")?;
    writeln!(buf)?;
    writeln!(buf, "    #[test]")?;
    writeln!(buf, "    fn trigram_weight_lookup_works() {{")?;
    writeln!(
        buf,
        "        // If the table is non-empty, the first entry must be findable."
    )?;
    writeln!(
        buf,
        "        if let Some(&(key, idf)) = TRIGRAM_WEIGHTS.first() {{"
    )?;
    writeln!(
        buf,
        "            assert_eq!(trigram_weight(key), Some(idf));"
    )?;
    writeln!(buf, "        }}")?;
    writeln!(buf, "    }}")?;
    writeln!(buf)?;
    writeln!(buf, "    #[test]")?;
    writeln!(buf, "    fn default_weight_is_positive() {{")?;
    writeln!(buf, "        const {{ assert!(DEFAULT_WEIGHT > 0.0) }};")?;
    writeln!(buf, "    }}")?;
    writeln!(buf)?;
    writeln!(buf, "    #[test]")?;
    writeln!(buf, "    fn all_idf_values_are_positive() {{")?;
    writeln!(
        buf,
        "        // IDF values must be finite and positive — DEFAULT_WEIGHT fallback applies"
    )?;
    writeln!(
        buf,
        "        // only when a key is absent, not as a substitute for invalid stored weights."
    )?;
    writeln!(
        buf,
        "        assert!(TRIGRAM_WEIGHTS.iter().all(|&(_, idf)| idf > 0.0 && idf.is_finite()));"
    )?;
    writeln!(buf, "    }}")?;
    writeln!(buf, "}}")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used, clippy::expect_used)]

    use super::*;
    use crate::types::{CorpusStats, TrigramWeight, TrigramWeightTable};

    fn sample_table() -> TrigramWeightTable {
        TrigramWeightTable {
            version: 1,
            generated_at: "unix:0".to_string(),
            corpus_stats: CorpusStats {
                total_files: 10,
                total_ngrams: 500,
                unique_ngrams: 3,
                deduplicated_files: 0,
                language_breakdown: vec![],
            },
            weights: vec![
                TrigramWeight {
                    trigram: 0x01_66_6E, // "\x01fn"
                    idf: 8.5,
                },
                TrigramWeight {
                    trigram: 0x66_6E_20, // "fn "
                    idf: 7.2,
                },
                TrigramWeight {
                    trigram: 0x70_75_62, // "pub"
                    idf: 6.1,
                },
            ],
        }
    }

    #[test]
    fn generate_valid_rust_source() {
        let table = sample_table();
        let source = build_weights_rs(&table).unwrap();

        // Must contain the correct const definition with u32 keys
        assert!(source.contains("pub const TRIGRAM_WEIGHTS: &[(u32, f32)] = &["));
        assert!(source.contains("pub const DEFAULT_WEIGHT: f32 = 1.0;"));
        assert!(source.contains("pub fn lookup_weight(key: u32"));
        assert!(source.contains("pub fn trigram_weight(key: u32)"));
        // Must contain trigram entries
        assert!(source.contains("0x01666E"));
        assert!(source.contains("0x666E20"));
        assert!(source.contains("0x707562"));
    }

    #[test]
    fn empty_weights_returns_error() {
        let dir = tempfile::tempdir().unwrap();
        let json_path = dir.path().join("trigram_weights.json");
        let out_path = dir.path().join("weights.rs");

        let empty_table = TrigramWeightTable {
            version: 1,
            generated_at: "unix:0".to_string(),
            corpus_stats: CorpusStats {
                total_files: 0,
                total_ngrams: 0,
                unique_ngrams: 0,
                deduplicated_files: 0,
                language_breakdown: vec![],
            },
            weights: vec![],
        };

        let json = serde_json::to_string(&empty_table).unwrap();
        std::fs::write(&json_path, json).unwrap();

        let err = generate_weights_rs(&json_path, &out_path).unwrap_err();
        assert!(err.to_string().contains("empty"));
    }

    #[test]
    fn version_zero_returns_error() {
        let dir = tempfile::tempdir().unwrap();
        let json_path = dir.path().join("trigram_weights.json");
        let out_path = dir.path().join("weights.rs");

        let table = TrigramWeightTable {
            version: 0,
            generated_at: "unix:0".to_string(),
            corpus_stats: CorpusStats {
                total_files: 10,
                total_ngrams: 500,
                unique_ngrams: 1,
                deduplicated_files: 0,
                language_breakdown: vec![],
            },
            weights: vec![TrigramWeight {
                trigram: 0x66_6E_20,
                idf: 8.5,
            }],
        };

        let json = serde_json::to_string(&table).unwrap();
        std::fs::write(&json_path, json).unwrap();

        let err = generate_weights_rs(&json_path, &out_path).unwrap_err();
        assert!(
            err.to_string().contains("version must be > 0"),
            "expected version error, got: {}",
            err
        );
    }

    #[test]
    fn negative_idf_returns_error() {
        let dir = tempfile::tempdir().unwrap();
        let json_path = dir.path().join("trigram_weights.json");
        let out_path = dir.path().join("weights.rs");

        let table = TrigramWeightTable {
            version: 1,
            generated_at: "unix:0".to_string(),
            corpus_stats: CorpusStats {
                total_files: 10,
                total_ngrams: 500,
                unique_ngrams: 1,
                deduplicated_files: 0,
                language_breakdown: vec![],
            },
            weights: vec![TrigramWeight {
                trigram: 0x66_6E_20,
                idf: -1.5,
            }],
        };

        let json = serde_json::to_string(&table).unwrap();
        std::fs::write(&json_path, json).unwrap();

        let err = generate_weights_rs(&json_path, &out_path).unwrap_err();
        assert!(
            err.to_string().contains("invalid IDF"),
            "expected invalid IDF error, got: {}",
            err
        );
    }
}
