//! Cursor hook protocol implementation.
//!
//! Cursor uses `beforeShellExecution` hooks via `.cursor/hooks.json`.
//! The hook reads JSON with command at top level (not nested under
//! tool_input like Claude Code), rewrites if matched, and responds
//! with `{ "permission": "allow", "updated_input": { "command": ... } }`.

use super::{HookInput, HookProtocol, HookSupport, InstallOpts, InstallResult, UninstallOpts};
use crate::cmd::session::AgentKind;

pub(crate) struct CursorHook;

impl HookProtocol for CursorHook {
    fn agent_kind(&self) -> AgentKind {
        AgentKind::Cursor
    }

    fn hook_support(&self) -> HookSupport {
        HookSupport::RealHook
    }

    fn parse_input(&self, json: &serde_json::Value) -> Option<HookInput> {
        // Cursor puts command at top level, not nested under tool_input
        let command = json.get("command").and_then(|c| c.as_str())?.to_string();
        Some(HookInput { command })
    }

    fn format_response(&self, rewritten_command: &str) -> serde_json::Value {
        serde_json::json!({
            "permission": "allow",
            "updated_input": {
                "command": rewritten_command
            }
        })
    }

    fn generate_script(&self, binary_path: &str, version: &str) -> String {
        format!(
            "#!/usr/bin/env bash\n\
             # skim-hook v{version}\n\
             # Generated by: skim init --agent cursor -- do not edit manually\n\
             export SKIM_HOOK_VERSION=\"{version}\"\n\
             exec \"{binary_path}\" rewrite --hook --agent cursor\n"
        )
    }

    fn install(&self, _opts: &InstallOpts) -> anyhow::Result<InstallResult> {
        // Actual install logic will be added in Phase 2 when multi-agent init lands.
        Ok(InstallResult {
            script_path: None,
            config_patched: false,
        })
    }

    fn uninstall(&self, _opts: &UninstallOpts) -> anyhow::Result<()> {
        // Actual uninstall logic will be added in Phase 2.
        Ok(())
    }
}

// ============================================================================
// Unit tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    fn hook() -> CursorHook {
        CursorHook
    }

    #[test]
    fn test_cursor_hook_is_real() {
        assert_eq!(hook().hook_support(), HookSupport::RealHook);
    }

    #[test]
    fn test_cursor_agent_kind() {
        assert_eq!(hook().agent_kind(), AgentKind::Cursor);
    }

    #[test]
    fn test_cursor_parse_input() {
        let json = serde_json::json!({
            "command": "cargo test --nocapture"
        });
        let result = hook().parse_input(&json);
        assert!(result.is_some());
        assert_eq!(result.unwrap().command, "cargo test --nocapture");
    }

    #[test]
    fn test_cursor_parse_input_missing_command() {
        let json = serde_json::json!({});
        assert!(hook().parse_input(&json).is_none());
    }

    #[test]
    fn test_cursor_parse_input_non_string_command() {
        let json = serde_json::json!({
            "command": 42
        });
        assert!(hook().parse_input(&json).is_none());
    }

    #[test]
    fn test_cursor_format_response() {
        let response = hook().format_response("skim test cargo");
        assert_eq!(response["permission"], "allow");
        assert_eq!(response["updated_input"]["command"], "skim test cargo");
    }

    #[test]
    fn test_cursor_format_response_no_hook_specific_output() {
        // Cursor uses permission/updated_input, not hookSpecificOutput
        let response = hook().format_response("skim test cargo");
        assert!(response.get("hookSpecificOutput").is_none());
    }

    #[test]
    fn test_cursor_generate_script_absolute_path() {
        let script = hook().generate_script("/usr/local/bin/skim", "1.2.0");
        assert!(script.contains("#!/usr/bin/env bash"));
        assert!(script.contains("# skim-hook v1.2.0"));
        assert!(script.contains("SKIM_HOOK_VERSION=\"1.2.0\""));
        assert!(script.contains("exec \"/usr/local/bin/skim\" rewrite --hook --agent cursor"));
        // Must use absolute path (quoted)
        assert!(script.contains("\"/usr/local/bin/skim\""));
    }

    #[test]
    fn test_cursor_generate_script_zero_stderr() {
        let script = hook().generate_script("/usr/local/bin/skim", "1.0.0");
        // No eprintln or echo to stderr in generated script
        assert!(!script.contains(">&2"));
        assert!(!script.contains("echo"));
        assert!(!script.contains("eprintln"));
    }

    #[test]
    fn test_cursor_generate_script_init_comment() {
        let script = hook().generate_script("/usr/local/bin/skim", "1.0.0");
        assert!(script.contains("skim init --agent cursor"));
    }

    #[test]
    fn test_cursor_install_stub() {
        let opts = InstallOpts {
            binary_path: "/usr/local/bin/skim".into(),
            version: "1.0.0".into(),
            config_dir: "/tmp/.cursor".into(),
            project_scope: false,
            dry_run: false,
        };
        let result = hook().install(&opts).unwrap();
        assert!(result.script_path.is_none());
        assert!(!result.config_patched);
    }

    #[test]
    fn test_cursor_uninstall_stub() {
        let opts = UninstallOpts {
            config_dir: "/tmp/.cursor".into(),
            force: false,
        };
        assert!(hook().uninstall(&opts).is_ok());
    }
}
