//! Gemini CLI hook protocol implementation.
//!
//! Implements the `HookProtocol` trait for Gemini CLI's BeforeTool event.
//!
//! Gemini CLI's hook protocol is nearly identical to Claude Code's:
//! - Config: `.gemini/settings.json`
//! - Event: `BeforeTool`
//! - Input: `{ "tool_name": "shell", "tool_input": { "command": "cargo test" } }`
//! - Response: `{ "decision": "allow", "tool_input": { "command": "skim test cargo" } }`
//!
//! SECURITY: Zero stderr in hook mode (GRANITE #361 lesson).
//! SECURITY: Absolute binary path in generated scripts (GRANITE #685 lesson).

use super::{HookInput, HookProtocol, HookSupport, InstallOpts, InstallResult, UninstallOpts};
use crate::cmd::session::AgentKind;

/// Gemini CLI hook implementation.
pub(crate) struct GeminiCliHook;

impl HookProtocol for GeminiCliHook {
    fn agent_kind(&self) -> AgentKind {
        AgentKind::GeminiCli
    }

    fn hook_support(&self) -> HookSupport {
        HookSupport::RealHook
    }

    fn parse_input(&self, json: &serde_json::Value) -> Option<HookInput> {
        let command = json
            .get("tool_input")
            .and_then(|ti| ti.get("command"))
            .and_then(|c| c.as_str())?
            .to_string();
        Some(HookInput { command })
    }

    fn format_response(&self, rewritten_command: &str) -> serde_json::Value {
        serde_json::json!({
            "decision": "allow",
            "tool_input": {
                "command": rewritten_command
            }
        })
    }

    fn generate_script(&self, binary_path: &str, version: &str) -> String {
        format!(
            "#!/usr/bin/env bash\n\
             # skim-hook v{version}\n\
             # Generated by: skim init --agent gemini -- do not edit manually\n\
             export SKIM_HOOK_VERSION=\"{version}\"\n\
             exec \"{binary_path}\" rewrite --hook --agent gemini\n",
            version = version,
            binary_path = binary_path,
        )
    }

    fn install(&self, _opts: &InstallOpts) -> anyhow::Result<InstallResult> {
        // Stub for Phase 0 -- full install logic in Phase 2 init changes
        Ok(InstallResult {
            script_path: None,
            config_patched: false,
        })
    }

    fn uninstall(&self, _opts: &UninstallOpts) -> anyhow::Result<()> {
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_gemini_hook_is_real() {
        let hook = GeminiCliHook;
        assert_eq!(hook.hook_support(), HookSupport::RealHook);
        assert_eq!(hook.agent_kind(), AgentKind::GeminiCli);
    }

    #[test]
    fn test_gemini_parse_input() {
        let hook = GeminiCliHook;
        let json = serde_json::json!({
            "tool_name": "shell",
            "tool_input": {
                "command": "cargo test"
            }
        });
        let input = hook.parse_input(&json).expect("should parse input");
        assert_eq!(input.command, "cargo test");
    }

    #[test]
    fn test_gemini_format_response() {
        let hook = GeminiCliHook;
        let response = hook.format_response("skim test cargo");
        assert_eq!(response["decision"], "allow");
        assert_eq!(response["tool_input"]["command"], "skim test cargo");
    }

    #[test]
    fn test_gemini_generate_script_has_absolute_path() {
        let hook = GeminiCliHook;
        let script = hook.generate_script("/usr/local/bin/skim", "1.2.3");
        assert!(
            script.contains("\"/usr/local/bin/skim\""),
            "script must use quoted absolute binary path, got: {script}"
        );
        assert!(
            script.contains("exec"),
            "script must use exec to replace shell process, got: {script}"
        );
    }

    #[test]
    fn test_gemini_generate_script_has_version() {
        let hook = GeminiCliHook;
        let script = hook.generate_script("/usr/local/bin/skim", "0.9.0");
        assert!(
            script.contains("SKIM_HOOK_VERSION=\"0.9.0\""),
            "script must export SKIM_HOOK_VERSION, got: {script}"
        );
        assert!(
            script.contains("# skim-hook v0.9.0"),
            "script must contain version comment, got: {script}"
        );
    }

    #[test]
    fn test_gemini_parse_input_missing_command() {
        let hook = GeminiCliHook;

        // Missing tool_input entirely
        let json = serde_json::json!({"tool_name": "shell"});
        assert!(hook.parse_input(&json).is_none());

        // tool_input present but no command
        let json = serde_json::json!({
            "tool_name": "shell",
            "tool_input": {}
        });
        assert!(hook.parse_input(&json).is_none());

        // command is not a string
        let json = serde_json::json!({
            "tool_name": "shell",
            "tool_input": {
                "command": 42
            }
        });
        assert!(hook.parse_input(&json).is_none());
    }

    #[test]
    fn test_gemini_generate_script_has_agent_flag() {
        let hook = GeminiCliHook;
        let script = hook.generate_script("/usr/local/bin/skim", "1.0.0");
        assert!(
            script.contains("--agent gemini"),
            "script must pass --agent gemini flag, got: {script}"
        );
    }

    #[test]
    fn test_gemini_generate_script_has_shebang() {
        let hook = GeminiCliHook;
        let script = hook.generate_script("/usr/local/bin/skim", "1.0.0");
        assert!(
            script.starts_with("#!/usr/bin/env bash"),
            "script must start with bash shebang, got: {script}"
        );
    }
}
