//! Tokio runtime, hyper accept loop, graceful shutdown, and per-connection
//! panic containment.
//!
//! ## AD-PXY-12 — Panic containment (AC9)
//!
//! Panic containment operates at two layers:
//!
//! 1. **tokio task isolation**: each `tokio::spawn`'d connection task is isolated
//!    by the tokio runtime — a panic in the task does not terminate the runtime or
//!    the accept loop. This is the load-bearing per-connection containment boundary.
//!
//! 2. **Per-transform call**: the `catch_unwind` in `handle_request` wraps
//!    every `stage.apply()` call inside `TransformPipeline::run` so a panicking
//!    stage falls back to byte-identical passthrough (AC9 / fail-open). The outer
//!    `catch_unwind` around `pipeline.run()` in `handle_request` catches any panic
//!    from the entire pipeline call as a second-level guard.
//!    Per-transform-call `catch_unwind` semantics: a panicking stage causes the
//!    WHOLE pipeline output to fall back to original bytes (conservatively safe).
//!
//! Note: there is intentionally NO per-connection `catch_unwind` wrapping the
//! hyper serve-connection `.await`. Wrapping only the connection-future CONSTRUCTOR
//! (not the await) is a no-op — the constructor cannot panic. Runtime task isolation
//! is sufficient; an explicit catch_unwind on a `!Unpin` async future requires
//! additional pinning complexity for no safety gain over tokio's own isolation.
//!
//! ## AD-PXY-13 — Connection cap: bounded TCP backpressure
//!
//! The chosen behavior is **bounded accept**: a semaphore limits the number
//! of concurrently-active connections. When the cap is reached, `accept()`
//! is not called until a connection slot is released — the OS TCP backlog
//! buffers the surplus (AC22). We do NOT return 503; that would require
//! answering the connection, spending resources we're trying to save. The
//! TCP backlog gives the client a natural retry via SO_BACKLOG.
//!
//! Named carve-out: the TCP-backpressure connection-cap behavior is NOT
//! a proxy-originated response. AC4/AC19b byte-identity tests are NOT
//! affected by this path (new connections wait without receiving any response).
//!
//! ## Lifecycle (AD-PXY-14)
//!
//! On SIGINT/SIGTERM:
//! 1. Accept loop stops immediately (no new connections accepted).
//! 2. In-flight connections drain for up to `config.graceful_drain` (5s).
//! 3. Process exits with code 0.
//!
//! Client-disconnect upstream cancel: when a client drops the connection
//! mid-stream, the per-connection task observes the write error and the
//! upstream request is cancelled implicitly via tokio task drop. In #303
//! there is no explicit `timeout(client_disconnect_cancel, …)` wrapper; the
//! 500ms `config.client_disconnect_cancel` bound is stored but not yet wired
//! (wiring is a #304 enhancement per config.rs:189-194).
//!
//! ## Structured logging (AC13)
//!
//! Request IDs are generated by the server layer using a monotonic counter
//! (+ process-unique prefix). They are NEVER derived from request headers
//! (no x-api-key echo / request-id forwarding from client headers).

use std::pin::Pin;
use std::sync::Arc;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::task::{Context, Poll};
use std::time::{Duration, Instant};

use bytes::Bytes;
use http_body_util::combinators::BoxBody;
use http_body_util::{BodyExt, Full};
use hyper::body::{Frame, Incoming, SizeHint};
use hyper::server::conn::http1;
use hyper::service::service_fn;
use hyper::{Request, Response, StatusCode};
use hyper_util::rt::TokioIo;
use tokio::net::TcpListener;
use tokio::sync::Semaphore;
use tokio::time::{Sleep, timeout};
use tracing::{info, warn};

/// Unified response body type: either a buffered error body (Full<Bytes>) or a
/// streaming upstream body (Incoming). Using BoxBody allows `handle_request` to
/// return streaming responses without buffering (AC5 / AC7).
type ProxyBody = BoxBody<Bytes, Box<dyn std::error::Error + Send + Sync + 'static>>;

/// Wrap a buffered body into the unified `ProxyBody` type.
fn full_body(b: impl Into<Bytes>) -> ProxyBody {
    Full::from(b.into())
        .map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })
        .boxed()
}

// ============================================================================
// IdleTimedBody — per-frame idle timeout for streaming upstream bodies (AC20)
// ============================================================================

/// A streaming body wrapper that enforces a per-frame idle timeout.
///
/// ## AD-PXY-20 — Mid-stream upstream stall (AC20 arm 2)
///
/// `hyper`'s upstream client returns a `Response<Incoming>` as soon as response
/// headers arrive; the body frames are streamed lazily afterward. Without this
/// wrapper, an upstream that sends headers + a partial body and then stalls the
/// connection open (no TCP reset, no data) will hold the client connection open
/// indefinitely.
///
/// `IdleTimedBody` wraps `Incoming` with a per-frame sleep that **resets** every
/// time a frame is successfully yielded. If no frame arrives within the
/// `idle_timeout` bound, the body stream is cleanly terminated (an error frame is
/// returned) so the client receives a truncated-but-closed stream rather than
/// hanging. This is fail-open: response headers have already been forwarded, so
/// we cannot send a 5xx — ending the body stream is the correct recovery action.
///
/// The reset-per-frame behavior is load-bearing for SSE: a legitimate slow SSE
/// stream that emits a frame every few seconds is NOT killed — only a gap
/// LONGER than `idle_timeout` triggers termination (AC5 / AC20 / AD-PXY-20).
///
/// The idle bound reuses `config.upstream_timeout`. This bounds BOTH the
/// time-to-headers phase (via `tokio::time::timeout` around `forward_request`)
/// AND the inter-frame idle gap of the streaming body (via this wrapper).
/// A single bound avoids introducing an empirically-baseless separate constant
/// (ADR-003 / PF-005). If a separate, shorter body-idle bound is required in
/// the future, it must be justified with documented evidence and cited here.
struct IdleTimedBody {
    inner: Incoming,
    idle_timeout: Duration,
    /// Per-frame sleep timer. Pinned because `Sleep` is `!Unpin`.
    sleep: Pin<Box<Sleep>>,
}

impl IdleTimedBody {
    fn new(inner: Incoming, idle_timeout: Duration) -> Self {
        let sleep = Box::pin(tokio::time::sleep(idle_timeout));
        Self {
            inner,
            idle_timeout,
            sleep,
        }
    }
}

impl http_body::Body for IdleTimedBody {
    type Data = Bytes;
    type Error = Box<dyn std::error::Error + Send + Sync + 'static>;

    fn poll_frame(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
    ) -> Poll<Option<Result<Frame<Bytes>, Self::Error>>> {
        // Safety: we project to inner (Unpin via Pin::new) and sleep (already pinned).
        // IdleTimedBody is never structurally pinned — projection is safe.
        let this = self.as_mut().get_mut();

        // Poll inner body first — if a frame is ready, reset the idle clock and return.
        // Use Pin::new: Incoming is Unpin.
        match Pin::new(&mut this.inner).poll_frame(cx) {
            Poll::Ready(Some(Ok(frame))) => {
                // Frame received — reset the idle sleep for the next inter-frame gap.
                let deadline = tokio::time::Instant::now() + this.idle_timeout;
                this.sleep.as_mut().reset(deadline);
                return Poll::Ready(Some(Ok(frame)));
            }
            Poll::Ready(Some(Err(e))) => {
                // Inner body error — propagate immediately.
                return Poll::Ready(Some(Err(Box::new(e) as _)));
            }
            Poll::Ready(None) => {
                // Body fully consumed — normal EOF.
                return Poll::Ready(None);
            }
            Poll::Pending => {
                // No frame yet — fall through to check the idle timer.
            }
        }

        // No frame ready. Poll the idle sleep.
        match this.sleep.as_mut().poll(cx) {
            Poll::Ready(()) => {
                // Idle timeout expired — no frame arrived within the bound.
                // Terminate the body stream cleanly. The client observes a
                // truncated-but-closed body rather than an indefinitely open socket.
                // Never panic — return an error frame instead (AC18 / AD-PXY-20).
                Poll::Ready(Some(Err(
                    "upstream body idle timeout: mid-stream stall terminated (AC20)".into(),
                )))
            }
            Poll::Pending => Poll::Pending,
        }
    }

    fn is_end_stream(&self) -> bool {
        false
    }

    fn size_hint(&self) -> SizeHint {
        self.inner.size_hint()
    }
}

/// Wrap a streaming `Incoming` body with a per-frame idle timeout into the
/// unified `ProxyBody` type.
///
/// See [`IdleTimedBody`] for the AC20 / AD-PXY-20 design rationale.
fn streaming_body_with_idle_timeout(b: Incoming, idle_timeout: Duration) -> ProxyBody {
    IdleTimedBody::new(b, idle_timeout).boxed()
}

// ============================================================================
// AnalyticsCompletionBody — observe-only stream-end wrapper (AD-PXY-23)
// ============================================================================

/// Observe-only response-completion body wrapper.
///
/// ## AD-PXY-23 — fire analytics at stream end, not at header time
///
/// The prior approach fired `analytics.on_request()` inside `handle_request`
/// at response-header time (`start.elapsed()` measured time-to-headers, not
/// time-to-stream-end). This wrapper replaces that fire site.
///
/// `AnalyticsCompletionBody` composes around the existing relay body (the
/// [`IdleTimedBody`]-wrapped `Incoming` produced by
/// `streaming_body_with_idle_timeout`). It:
/// - Delegates every `poll_frame` unchanged (ADR-007 egress losslessness — the
///   wrapper never reads or mutates forwarded bytes).
/// - Fires `analytics.on_request(&event)` exactly once at the first of:
///   - Clean EOF: `poll_frame` returns `Poll::Ready(None)`.
///   - Drop: called when the body is dropped (mid-stream client disconnect or
///     body error surfaced by the idle-timeout wrapper), via `Drop::drop`.
/// - A boolean guard (`fired`) prevents double-fire if EOF is followed by Drop.
/// - Computes `duration = start.elapsed()` at fire time, making `duration_ms`
///   measure request receipt → final relayed frame / stream end (AC4/AC20).
///
/// The wrapper never reads or mutates forwarded bytes. The non-blocking
/// `analytics.on_request()` call is wrapped in `catch_unwind` (AC9).
///
/// ## ADR-007 losslessness
///
/// This wrapper adds only observe-only structure to the egress relay path.
/// Frame bytes are forwarded byte-identical to the upstream response. The
/// `round-trip decompress(compress(x))==x` guarantee mandated by ADR-007 lives
/// in the compression engines (#304/#427), which this ticket does not modify.
struct AnalyticsCompletionBody {
    inner: ProxyBody,
    /// The partially-built event (duration == Duration::ZERO; set at fire time).
    event: ProxyEvent,
    analytics: Arc<dyn AnalyticsHook>,
    start: Instant,
    /// Prevents double-fire when EOF `poll_frame` is followed by `Drop`.
    fired: bool,
}

impl AnalyticsCompletionBody {
    fn new(
        inner: ProxyBody,
        event: ProxyEvent,
        analytics: Arc<dyn AnalyticsHook>,
        start: Instant,
    ) -> Self {
        Self {
            inner,
            event,
            analytics,
            start,
            fired: false,
        }
    }

    /// Fire the analytics event exactly once, computing duration at call time.
    ///
    /// AD-PXY-23: `duration = start.elapsed()` is evaluated here so it measures
    /// the full request → stream-end wall time. The boolean guard prevents
    /// double-fire. `catch_unwind` satisfies AC9 (panicking hook cannot fail
    /// the relay).
    fn fire(&mut self) {
        if !self.fired {
            self.fired = true;
            let mut event = self.event.clone();
            event.duration = self.start.elapsed();
            let analytics = Arc::clone(&self.analytics);
            // AC9: catch_unwind ensures a panicking hook does not propagate.
            // AD-PXY-17: on_request must not block (ChannelAnalyticsHook is
            // the non-blocking implementation; NoopAnalyticsHook is zero-cost).
            let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                analytics.on_request(&event);
            }));
        }
    }
}

/// Drop-based fire: covers mid-stream client disconnect or body error.
///
/// AD-PXY-23: fires on the first of {clean EOF, Drop}. The `fired` guard
/// prevents double-fire when the clean-EOF path already fired.
impl Drop for AnalyticsCompletionBody {
    fn drop(&mut self) {
        self.fire();
    }
}

impl http_body::Body for AnalyticsCompletionBody {
    type Data = Bytes;
    type Error = Box<dyn std::error::Error + Send + Sync + 'static>;

    fn poll_frame(
        mut self: Pin<&mut Self>,
        cx: &mut Context<'_>,
    ) -> Poll<Option<Result<Frame<Bytes>, Self::Error>>> {
        // Safety: AnalyticsCompletionBody is Unpin (all fields are Unpin).
        // get_mut() is safe here.
        let this = self.as_mut().get_mut();
        // BoxBody is Unpin — Pin::new is safe.
        match Pin::new(&mut this.inner).poll_frame(cx) {
            // AD-PXY-23: clean EOF — fire analytics at stream end.
            Poll::Ready(None) => {
                this.fire();
                Poll::Ready(None)
            }
            // Pass through all other outcomes unchanged (ADR-007 losslessness).
            other => other,
        }
    }

    fn is_end_stream(&self) -> bool {
        self.inner.is_end_stream()
    }

    fn size_hint(&self) -> http_body::SizeHint {
        self.inner.size_hint()
    }
}

// ============================================================================
// Tier derivation helpers (AD-PXY-21)
// ============================================================================

/// Derive the request-level compression tier from collected `DecisionRecord`s.
///
/// ## AD-PXY-21 / Cross-Plan Amendment #3
///
/// Filters to the `"block-router"` component only, excluding any
/// `CacheAlignStage` records (#306) that share the same collector sink. Rule:
/// - any `Degraded` → `RequestTier::Degraded`
/// - else any `Full` → `RequestTier::Full`
/// - else `RequestTier::Passthrough`
///
/// This is pure in-memory aggregation of a small `Vec` — no I/O, no token
/// counting on the request path (constraint 1).
fn derive_tier(records: &[DecisionRecord]) -> RequestTier {
    let mut has_degraded = false;
    let mut has_full = false;

    for record in records {
        // Cross-Plan Amendment #3: filter to block-router component only.
        // A discriminating test (in proxy_analytics_tier_tests.rs) asserts that
        // a non-"block-router" component emitting Full does NOT affect the tier.
        if record.component != "block-router" {
            continue;
        }
        #[allow(unreachable_patterns)] // OutcomeReason is #[non_exhaustive]
        match record.reason {
            OutcomeReason::Degraded => has_degraded = true,
            OutcomeReason::Full => has_full = true,
            _ => {}
        }
    }

    if has_degraded {
        RequestTier::Degraded
    } else if has_full {
        RequestTier::Full
    } else {
        RequestTier::Passthrough
    }
}

/// Project one `DecisionRecord` into a compact `BlockDecisionProjection`.
///
/// ## AD-AN-13 / AD-PXY-21
///
/// The outcome string is derived from `OutcomeReason` to a stable static str.
/// `bytes_in` / `bytes_out` are copied directly (always present, exact, and
/// additive across blocks — the byte-reconciliation invariant).
fn project_decision(record: &DecisionRecord) -> BlockDecisionProjection {
    #[allow(unreachable_patterns)] // OutcomeReason is #[non_exhaustive]
    let outcome = match record.reason {
        OutcomeReason::Full => "full",
        OutcomeReason::Degraded => "degraded",
        OutcomeReason::Passthrough => "passthrough",
        OutcomeReason::FailedOpen => "failed_open",
        OutcomeReason::PolicyPassthrough => "policy_passthrough",
        OutcomeReason::LossyRejected => "lossy_rejected",
        _ => "unknown",
    };
    BlockDecisionProjection {
        component: record.component,
        outcome,
        bytes_in: record.bytes_in,
        bytes_out: record.bytes_out,
    }
}

/// Fire a distinct analytics event for a request that passed the transform
/// but failed upstream (AD-PXY-25).
///
/// ## AD-PXY-24 / AD-PXY-25 — three-outcome recording predicate
///
/// Called at the post-transform 502/504 return sites:
/// - 502 no-upstream (empty `upstream_url`)
/// - 504 upstream timeout
/// - 502 bad-URL / connection-error
///
/// The event carries `upstream_error_status = Some(status)` and NULL token
/// columns (token counting is not performed for these rows). Its per-block
/// `block_decisions` are still recorded (the transform ran), so the
/// byte-reconciliation invariant (AD-AN-13) holds.
///
/// This function uses a bounded non-blocking `on_request` call (AC14) wrapped
/// in `catch_unwind` (AC9). It must NEVER block the request path.
#[allow(clippy::too_many_arguments)]
fn fire_upstream_error_event(
    analytics: &Arc<dyn AnalyticsHook>,
    provider: &ProxyProvider,
    model: &Option<String>,
    tier: RequestTier,
    raw_body: &Bytes,
    final_body: &Bytes,
    block_decisions: &[BlockDecisionProjection],
    status: u16,
    start: Instant,
) {
    let event = ProxyEvent::new(
        provider.clone(),
        model.clone(),
        None, // turn_id — always None until #344
        tier,
        raw_body.clone(),
        final_body.clone(),
        block_decisions.to_vec(),
        Some(status), // upstream_error_status (AD-PXY-25)
        start.elapsed(),
    );
    // AC9 / AD-PXY-17: catch_unwind + non-blocking.
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        analytics.on_request(&event);
    }));
}

use rskim_contract::log::{DecisionRecord, MockSink, OutcomeReason};

use crate::analytics::{AnalyticsHook, BlockDecisionProjection, ProxyEvent, RequestTier};
use crate::authmode::classify_auth;
use crate::config::ProxyConfig;
use crate::detect::{ProxyProvider, detect_model, detect_provider};
use crate::errors::ProxyError;
use crate::forward::{ForwardError, UpstreamClient, forward_request, is_hop_by_hop};
use crate::health::{ReadinessState, is_health_path, livez_response, readyz_response};
use crate::seam::{HeaderView, TransformContext, TransformPipeline};

// ============================================================================
// Connection cap (AD-PXY-13)
// ============================================================================

/// Maximum concurrent connections.
///
/// When this cap is reached, new connections wait in the OS TCP backlog
/// (bounded-accept strategy, AD-PXY-13). The cap protects against memory
/// exhaustion from connection floods.
///
/// Evidence: chosen as a generous upper bound for a local AI proxy (AI
/// requests are large, slow, and few — not high-fan-out HTTP/REST traffic).
/// A local proxy on developer hardware with 16GB RAM should safely handle
/// 512 concurrent 64MiB bodies. Oversize bodies stream through, so the
/// per-connection memory is bounded by the transform buffer (64MiB max, but
/// most AI requests are ~10KB).
pub const DEFAULT_CONNECTION_CAP: usize = 512;

// ============================================================================
// Request-ID generation (AC13 — never header-derived)
// ============================================================================

/// Per-process monotonic request ID counter.
///
/// Combined with the process-start nonce to produce collision-unlikely IDs
/// that are never derived from request headers (AC13 / AD-PXY-08).
static REQUEST_ID_COUNTER: AtomicU64 = AtomicU64::new(0);

/// Generate a process-unique request ID.
///
/// Format: `px-{counter}` where counter is monotonically increasing per process.
/// IDs are NOT derived from any request header — this prevents the x-api-key echo
/// anti-pattern (#301 AC12 guard / AC13).
fn next_request_id() -> String {
    let n = REQUEST_ID_COUNTER.fetch_add(1, Ordering::Relaxed);
    format!("px-{n}")
}

// ============================================================================
// Static response helpers
// ============================================================================

fn json_response(status: StatusCode, body: impl Into<Bytes>) -> Response<ProxyBody> {
    Response::builder()
        .status(status)
        .header(hyper::header::CONTENT_TYPE, "application/json")
        .body(full_body(body.into()))
        .unwrap_or_else(|_| {
            // Builder error (invalid header value) — emit a minimal 500.
            // This branch is unreachable: status comes from a const and the
            // content-type value is a valid static string. If it somehow fails,
            // return a minimal error without panicking (AC9 — never panic on path).
            Response::new(full_body(Bytes::from_static(b"{}")))
        })
}

// ============================================================================
// Per-request handler
// ============================================================================

/// Handle a single HTTP request.
///
/// This function is called once per request within a connection task.
/// It performs:
/// 1. Health endpoint short-circuit (livez/readyz/health).
/// 2. Request body buffering (up to max_body_bytes; oversize or read-error → 400,
///    named carve-out per lib.rs; byte-identical streaming passthrough tracked in #304).
/// 3. Provider detection + auth classification.
/// 4. Transform pipeline (identity in #303; #304 injects BlockRouter).
/// 5. Header rewrite (hop-by-hop strip, host rewrite — no Via, AD-PXY-15).
/// 6. Forward to upstream (within upstream_timeout).
/// 7. Stream response body chunk-by-chunk to client.
/// 8. Record readiness outcome + fire analytics hook.
///
/// ## AC13 — request_id is never header-derived
///
/// The request ID is generated by [`next_request_id`]. The incoming
/// `x-request-id` / `x-correlation-id` headers (if any) are forwarded to the
/// upstream byte-identically but are NEVER used as the proxy's own correlation ID.
async fn handle_request(
    req: Request<Incoming>,
    config: Arc<ProxyConfig>,
    pipeline: Arc<TransformPipeline>,
    upstream_client: Arc<UpstreamClient>,
    readiness: Arc<ReadinessState>,
    analytics: Arc<dyn AnalyticsHook>,
) -> Result<Response<ProxyBody>, std::convert::Infallible> {
    let request_id = next_request_id();
    let start = Instant::now();

    // ---- Health short-circuit ----
    let path = req.uri().path().to_owned();
    if is_health_path(&path) {
        let response = match path.as_str() {
            "/livez" => {
                let (status, body) = livez_response();
                json_response(StatusCode::from_u16(status).unwrap_or(StatusCode::OK), body)
            }
            // AC18: no panics on the forwarding path — use a defensive fallback
            // for any is_health_path variant not explicitly matched above.
            // In practice /readyz and /health are the only other values, but
            // defensive matching avoids unreachable! (which would panic).
            _ => {
                let (status, body) = readyz_response(&readiness);
                json_response(
                    StatusCode::from_u16(status).unwrap_or(StatusCode::SERVICE_UNAVAILABLE),
                    body,
                )
            }
        };
        return Ok(response);
    }

    // ---- Collect request parts ----
    let (parts, body) = req.into_parts();

    // Collect headers as (String, String) pairs for HeaderView.
    let header_pairs: Vec<(String, String)> = parts
        .headers
        .iter()
        .filter_map(|(name, value)| {
            let v = value.to_str().ok()?.to_owned();
            Some((name.as_str().to_owned(), v))
        })
        .collect();

    // Classify auth (header-shape only — values never read for logging, AC13).
    let auth_mode = classify_auth(header_pairs.iter().map(|(k, v)| (k.as_str(), v.as_str())));

    // ---- Buffer body (up to max_body_bytes via Limited, AD-PXY-10) ----
    //
    // http_body_util::Limited enforces the max_body_bytes cap.
    //
    // Two distinct error cases:
    //   (a) LengthLimitError (body exceeded the cap): the client sent a valid but
    //       large body. AD-PXY-10 / AC3 require fail-open: return 400 in #303.
    //       True streaming-passthrough (AC3 byte-identical forward for oversize) is
    //       tracked in #304; that path requires streaming the original body through
    //       the forward layer without buffering the full body first.
    //   (b) Read/IO error (client dropped mid-send): the connection is already gone.
    //       Returning any response is best-effort; we return 400 and close.
    //
    // Named carve-out (#303): proxy-originated 400 for oversize/read-error is an
    // explicit carve-out on the lib.rs list (alongside 502/504). AC4/AC19b byte-
    // identity tests exclude this path by construction (test bodies are tiny).
    use http_body_util::Limited;
    let limited = Limited::new(body, config.max_body_bytes);
    let body_bytes = match limited.collect().await {
        Ok(collected) => collected.to_bytes(),
        Err(e) => {
            // Both LengthLimitError and IO errors surface here. In both cases we
            // cannot safely fabricate or forward — return 400 and close.
            warn!(request_id = %request_id, error = %e, "failed to read request body (oversize or client disconnect) — returning 400");
            return Ok(json_response(
                StatusCode::BAD_REQUEST,
                r#"{"error":"request body read error"}"#,
            ));
        }
    };

    // ---- Provider detection ----
    let sniff_limit = std::cmp::min(body_bytes.len(), crate::detect::SHAPE_SNIFF_LIMIT);
    let provider = detect_provider(&path, &body_bytes[..sniff_limit]);

    // AD-PXY-22: extract model string verbatim from the same bounded sniff window.
    // Returns None when undetected (non-UTF-8, no "model" key, or parse failure).
    let model = detect_model(&body_bytes[..sniff_limit]);

    // ---- 502 for Unknown provider with no default upstream (D8 / AC3) ----
    // AD-PXY-24: pre-transform failure → NO analytics event (transform never ran).
    if provider == ProxyProvider::Unknown && config.upstream_default.is_none() {
        warn!(
            request_id = %request_id,
            "Unknown provider and no default upstream configured — returning 502 (D8/AC3)"
        );
        return Ok(json_response(
            StatusCode::BAD_GATEWAY,
            r#"{"error":"no default upstream configured for Unknown provider"}"#,
        ));
    }

    // ---- Transform pipeline (with collecting sink for tier derivation) ----
    //
    // AD-PXY-21: replace NullSink with a request-scoped MockSink so per-block
    // DecisionRecords are captured for tier derivation and the
    // proxy_block_decisions detail table. MockSink is always available from
    // rskim_contract (not feature-gated).
    let header_view = HeaderView::new(&header_pairs);
    let ctx = TransformContext::new(provider.clone(), auth_mode, &request_id, &header_view);

    let collecting_sink = MockSink::new();

    // AC9: per-transform panic containment — catch_unwind around pipeline.run.
    // A panicking stage falls back to the original body bytes (fail-open).
    // pipeline.run takes Vec<u8>, so convert from Bytes.
    let transformed_body = {
        let body_vec = body_bytes.to_vec();
        let pipeline_result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            pipeline.run(body_vec, &ctx, &collecting_sink)
        }));
        match pipeline_result {
            Ok(outcome) => Bytes::from(outcome.bytes),
            Err(_panic) => {
                warn!(request_id = %request_id, "transform stage panicked — using original body (AC9 fail-open)");
                body_bytes.clone()
            }
        }
    };

    // AD-PXY-21: drain the collecting sink and derive the request tier.
    // Cross-Plan Amendment #3: derive_tier filters to "block-router" component
    // to exclude future CacheAlignStage (#306) records.
    let collected_records = collecting_sink.drain();
    let tier = derive_tier(&collected_records);
    // Project each record to the compact per-block representation for the
    // proxy_block_decisions detail table (AD-AN-13).
    let block_decisions: Vec<BlockDecisionProjection> =
        collected_records.iter().map(project_decision).collect();

    // ---- Determine upstream URL ----
    // Map provider to the key used in ProxyConfig::upstream_for.
    // #[non_exhaustive]: the wildcard arm is required for non_exhaustive enums matched
    // outside the defining crate (AC24 / AD-PXY-02). Future variants fall back to
    // the default upstream via an empty key (no per-provider override → upstream_for
    // returns upstream_default).
    #[allow(unreachable_patterns)]
    let provider_key = match &provider {
        ProxyProvider::Anthropic => "anthropic",
        ProxyProvider::OpenAI => "openai",
        _ => "",
    };
    // upstream_for already falls back to upstream_default when provider_key has no entry.
    let upstream_url = config.upstream_for(provider_key).unwrap_or("").to_owned();

    if upstream_url.is_empty() {
        // AD-PXY-25: post-transform 502 (no upstream configured) — fire distinct
        // transformed-but-upstream-errored event. The transform ran (line above),
        // so we have tier and block_decisions.
        fire_upstream_error_event(
            &analytics,
            &provider,
            &model,
            tier,
            &body_bytes,
            &transformed_body,
            &block_decisions,
            502,
            start,
        );
        return Ok(json_response(
            StatusCode::BAD_GATEWAY,
            r#"{"error":"no upstream configured"}"#,
        ));
    }

    // ---- Forward request to upstream ----
    // AD-PXY-14: upstream_timeout = 60s (evidence-cited in config.rs).
    let forward_result = timeout(
        config.upstream_timeout,
        forward_request(parts, transformed_body.clone(), &upstream_url, &upstream_client),
    )
    .await;

    let upstream_response = match forward_result {
        Err(_timeout) => {
            // Upstream did not respond within the configured timeout → 504 (AC20).
            // Log the actual operative timeout from config (not the default const) so
            // operators who override --upstream-timeout see the correct value.
            readiness.record_failure();
            warn!(
                request_id = %request_id,
                timeout_secs = %config.upstream_timeout.as_secs(),
                "upstream timeout (AC20)"
            );
            // AD-PXY-25: post-transform 504 — fire distinct upstream-errored event.
            fire_upstream_error_event(
                &analytics,
                &provider,
                &model,
                tier,
                &body_bytes,
                &transformed_body,
                &block_decisions,
                504,
                start,
            );
            return Ok(json_response(
                StatusCode::GATEWAY_TIMEOUT,
                r#"{"error":"upstream timeout","code":"504"}"#,
            ));
        }
        Ok(Err(ForwardError::BadUpstreamUrl(u))) => {
            readiness.record_failure();
            warn!(request_id = %request_id, upstream = %u, "bad upstream URL");
            // AD-PXY-25: post-transform 502 (bad upstream URL) — fire distinct event.
            fire_upstream_error_event(
                &analytics,
                &provider,
                &model,
                tier,
                &body_bytes,
                &transformed_body,
                &block_decisions,
                502,
                start,
            );
            return Ok(json_response(
                StatusCode::BAD_GATEWAY,
                r#"{"error":"bad upstream URL"}"#,
            ));
        }
        Ok(Err(ForwardError::Upstream(e))) => {
            // Connection refused, TCP reset, etc. → relay as 502 (AC10).
            // Use serde_json to build the body so the upstream error string is
            // correctly JSON-escaped even if it contains quotes, backslashes, or
            // control characters (A03 — escape output for its context).
            readiness.record_failure();
            warn!(request_id = %request_id, error = %e, "upstream connection error (AC10)");
            // AD-PXY-25: post-transform 502 (connection error) — fire distinct event.
            fire_upstream_error_event(
                &analytics,
                &provider,
                &model,
                tier,
                &body_bytes,
                &transformed_body,
                &block_decisions,
                502,
                start,
            );
            let body = serde_json::json!({"error": "upstream error", "detail": e}).to_string();
            return Ok(json_response(StatusCode::BAD_GATEWAY, body));
        }
        Ok(Ok(resp)) => resp,
    };

    // ---- Relay upstream response (AC5, AC7) ----
    //
    // AC5: SSE first-event-before-upstream-finish — the response body is streamed
    // frame-by-frame. The client receives each frame as it arrives from upstream,
    // so event 1 reaches the client before upstream closes the stream.
    //
    // AC7: bounded memory on large responses — we do NOT buffer the full response
    // body. The `Incoming` body is forwarded directly as a streaming `BoxBody`.
    // A slow client naturally applies TCP backpressure to the upstream read.
    //
    // Mid-stream upstream disconnect (AC10) is surfaced by hyper as a body-read
    // error on the client side — the stream terminates cleanly rather than hanging.
    let (resp_parts, resp_body) = upstream_response.into_parts();
    let resp_status = resp_parts.status;
    let resp_headers = resp_parts.headers.clone();

    // Record readiness success (upstream responded, even if 5xx).
    readiness.record_success();

    // ---- Build relay response with streaming body ----
    //
    // Content-Length is dropped here for symmetry with the request-forward path
    // (forward.rs drops it so hyper re-derives framing from the actual body).
    // For #303 the response body is forwarded byte-identical, so the upstream
    // content-length would be correct — but dropping it prevents a latent
    // correctness hazard when #304 re-frames response bodies (compression changes
    // byte counts, and an upstream content-length left in place would cause the
    // client to hang waiting for bytes that never arrive). Mirror the request-path
    // policy now rather than letting #304 inherit a silent framing trap.
    let mut relay_builder = Response::builder().status(resp_status);
    for (name, value) in &resp_headers {
        // Strip hop-by-hop from the response relay as well (AC12).
        // Also drop content-length so hyper re-derives framing from the actual body.
        if !is_hop_by_hop(name.as_str()) && name != hyper::header::CONTENT_LENGTH {
            relay_builder = relay_builder.header(name, value);
        }
    }

    // AD-PXY-20 (AC20 arm 2): wrap the upstream body with a per-frame idle
    // timeout so that a mid-stream upstream stall (headers delivered, then
    // socket held open with no data) terminates cleanly within the bound.
    // `config.upstream_timeout` bounds BOTH time-to-headers (the `timeout()`
    // above) AND the inter-frame idle gap here. See [`IdleTimedBody`] for the
    // full rationale and why reusing the same bound avoids an
    // empirically-baseless constant (ADR-003 / PF-005).
    let relay_response = relay_builder
        .body(streaming_body_with_idle_timeout(
            resp_body,
            config.upstream_timeout,
        ))
        .unwrap_or_else(|_| {
            json_response(
                StatusCode::BAD_GATEWAY,
                r#"{"error":"response build failed"}"#,
            )
        });

    // ---- Wrap relay body with AnalyticsCompletionBody (AD-PXY-23) ----
    //
    // AD-PXY-23: fire the analytics event at clean EOF or Drop (not at header
    // time), so duration captures the full stream-to-client time. Every
    // poll_frame is delegated unchanged — ADR-007 egress losslessness.
    //
    // AD-PXY-24: three-outcome recording predicate — success path records a
    // normal relay row here. Pre-transform failures (400 paths above) fire NO
    // event. Post-transform 502/504 sites fire a distinct upstream-errored
    // event (AD-PXY-25) before returning.
    //
    // Build the ProxyEvent with duration=ZERO; AnalyticsCompletionBody fills
    // in the real elapsed time at fire() time (AC15 / AD-PXY-17).
    let (relay_parts, relay_inner_body) = relay_response.into_parts();
    let event = ProxyEvent::new(
        provider,
        model,
        None, // turn_id — always None until #344 derives it
        tier,
        body_bytes,
        transformed_body,
        block_decisions,
        None, // upstream_error_status: None for the success path
        Duration::ZERO,
    );
    let instrumented_body =
        AnalyticsCompletionBody::new(relay_inner_body, event, analytics, start).boxed();
    Ok(Response::from_parts(relay_parts, instrumented_body))
}

// ============================================================================
// Graceful shutdown signal
// ============================================================================

/// Shared shutdown flag.
///
/// Set to `true` by the signal handler; polled by the accept loop.
/// Reserved for future use by a public shutdown API (AC23 / AD-PXY-14).
#[allow(dead_code)]
pub(crate) struct ShutdownFlag(Arc<AtomicBool>);

#[allow(dead_code)]
impl ShutdownFlag {
    fn new() -> (Self, Arc<AtomicBool>) {
        let flag = Arc::new(AtomicBool::new(false));
        (Self(Arc::clone(&flag)), flag)
    }

    fn is_set(&self) -> bool {
        self.0.load(Ordering::SeqCst)
    }
}

// ============================================================================
// Server start
// ============================================================================

/// Inner accept loop shared by `run_server` and `run_server_with_listener`.
///
/// Accepts connections on an already-bound `listener` until a SIGINT/SIGTERM
/// is received, then drains in-flight connections for up to
/// `config.graceful_drain` before returning.
///
/// All public API is on the callers (`run_server` / `run_server_with_listener`);
/// this function is an implementation detail and not part of the stable API.
async fn serve_listener(
    listener: TcpListener,
    config: Arc<ProxyConfig>,
    pipeline: Arc<TransformPipeline>,
    analytics: Arc<dyn AnalyticsHook>,
    upstream_client: Arc<UpstreamClient>,
    readiness: Arc<ReadinessState>,
) -> Result<(), ProxyError> {
    // Connection-cap semaphore (AD-PXY-13 bounded-accept).
    let connection_cap = Arc::new(Semaphore::new(DEFAULT_CONNECTION_CAP));

    // Shutdown signal handling.
    // We use a simple tokio select! approach: wait for either an accepted
    // connection or a shutdown signal.
    let shutdown = Arc::new(AtomicBool::new(false));
    let shutdown_clone = Arc::clone(&shutdown);

    // Spawn the SIGINT/SIGTERM handler task.
    tokio::spawn(async move {
        wait_for_shutdown_signal().await;
        shutdown_clone.store(true, Ordering::SeqCst);
        info!("shutdown signal received — stopping accept loop");
    });

    // Track in-flight connections for graceful drain.
    let in_flight = Arc::new(AtomicU64::new(0));

    loop {
        // Check shutdown flag before accepting.
        if shutdown.load(Ordering::SeqCst) {
            info!("shutdown: stopping accept loop");
            break;
        }

        // Acquire a connection slot (bounded-accept, AD-PXY-13).
        // acquire_owned().await parks the task until a permit is available — no
        // busy-loop or CPU-spin. The OS TCP backlog buffers surplus connections
        // while we wait. The shutdown flag is re-checked each loop iteration (the
        // `if shutdown` guard at the top of the loop handles clean exit).
        let permit = match connection_cap.clone().acquire_owned().await {
            Ok(p) => p,
            Err(_) => break, // semaphore closed (not expected in normal flow)
        };

        // Accept with a short timeout so we can check the shutdown flag.
        let accept_result = timeout(Duration::from_millis(100), listener.accept()).await;

        match accept_result {
            Err(_timeout) => {
                // No incoming connection in 100ms — loop back to check shutdown.
                drop(permit);
                continue;
            }
            Ok(Err(e)) => {
                warn!(error = %e, "accept error");
                drop(permit);
                continue;
            }
            Ok(Ok((stream, peer_addr))) => {
                let config = Arc::clone(&config);
                let pipeline = Arc::clone(&pipeline);
                let upstream_client = Arc::clone(&upstream_client);
                let readiness = Arc::clone(&readiness);
                let analytics = Arc::clone(&analytics);
                let in_flight = Arc::clone(&in_flight);

                in_flight.fetch_add(1, Ordering::Relaxed);

                // Per-connection task (AD-PXY-12 / AC9).
                //
                // Panic containment: tokio task isolation is the per-connection
                // boundary. A panic in the spawned task terminates only that task;
                // the runtime and the accept loop continue. The per-transform
                // catch_unwind in handle_request (around pipeline.run) is the
                // per-transform boundary. Wrapping `conn.await` in catch_unwind
                // is non-trivial for !Unpin futures and provides no additional
                // safety over tokio's own task isolation.
                tokio::spawn(async move {
                    let _permit = permit; // drops when task finishes (releases slot)
                    // Decrement in-flight counter when the task finishes.
                    // Use a simple RAII wrapper to ensure the counter is decremented
                    // even if the async block exits unexpectedly.
                    struct InFlightGuard(Arc<AtomicU64>);
                    impl Drop for InFlightGuard {
                        fn drop(&mut self) {
                            self.0.fetch_sub(1, Ordering::Relaxed);
                        }
                    }
                    let _in_flight_guard = InFlightGuard(Arc::clone(&in_flight));

                    let io = TokioIo::new(stream);
                    let service = service_fn(move |req| {
                        handle_request(
                            req,
                            Arc::clone(&config),
                            Arc::clone(&pipeline),
                            Arc::clone(&upstream_client),
                            Arc::clone(&readiness),
                            Arc::clone(&analytics),
                        )
                    });

                    let conn = http1::Builder::new().serve_connection(io, service);
                    if let Err(e) = conn.await {
                        // Client disconnect or protocol error — log and continue.
                        // The tokio runtime survives task-level panics (AC9).
                        tracing::debug!(
                            peer = %peer_addr,
                            error = %e,
                            "connection error (client disconnect or protocol)"
                        );
                    }
                });
            }
        }
    }

    // Graceful drain (AC23 / AD-PXY-14).
    info!(
        drain_secs = %config.graceful_drain.as_secs(),
        "draining in-flight connections"
    );
    let drain_deadline = Instant::now() + config.graceful_drain;
    while in_flight.load(Ordering::Relaxed) > 0 && Instant::now() < drain_deadline {
        tokio::time::sleep(Duration::from_millis(50)).await;
    }

    let remaining = in_flight.load(Ordering::Relaxed);
    if remaining > 0 {
        warn!(remaining, "graceful drain timeout — forcing exit");
    } else {
        info!("graceful drain complete");
    }

    Ok(())
}

/// Start the HTTP proxy server.
///
/// Binds to `config.bind_addr`, accepts connections (bounded by
/// [`DEFAULT_CONNECTION_CAP`]), and handles requests via [`handle_request`].
///
/// Blocks until SIGINT/SIGTERM is received. On signal:
/// 1. Stops accepting new connections.
/// 2. Waits for in-flight connections to drain (up to `config.graceful_drain`).
/// 3. Returns `Ok(())`.
///
/// ## AC23 — Graceful shutdown
///
/// The drain window is `config.graceful_drain` (5s, evidence in config.rs).
/// In-flight streams are given this window; new connections are refused after
/// the signal is received.
///
/// ## AC22 — Connection cap
///
/// A `Semaphore` with [`DEFAULT_CONNECTION_CAP`] permits enforces the cap.
/// When all permits are held, `accept()` blocks (TCP backpressure — AD-PXY-13).
pub async fn run_server(
    config: ProxyConfig,
    pipeline: TransformPipeline,
    analytics: Arc<dyn AnalyticsHook>,
) -> Result<(), ProxyError> {
    let bind_addr = config.bind_addr;
    let config = Arc::new(config);
    let pipeline = Arc::new(pipeline);
    let readiness = ReadinessState::new();
    let upstream_client =
        Arc::new(UpstreamClient::new().map_err(|e| ProxyError::TlsConfig(e.to_string()))?);

    // Bind the listener.
    let listener = TcpListener::bind(bind_addr)
        .await
        .map_err(|e| ProxyError::BindFailed {
            addr: bind_addr.to_string(),
            source: e,
        })?;

    info!(addr = %bind_addr, "proxy listening");

    serve_listener(
        listener,
        config,
        pipeline,
        analytics,
        upstream_client,
        readiness,
    )
    .await
}

/// Like [`run_server`] but accepts a pre-bound listener, bypassing the bind
/// step and the port-range validation enforced by [`ProxyConfig`].
///
/// Intended for integration tests that obtain an OS-assigned port by binding
/// to `127.0.0.1:0` — the OS guarantees each `bind(0)` call returns a unique
/// port, eliminating the TOCTOU race that a probe-then-bind approach has under
/// parallel nextest execution (each test runs in its own process, so a
/// process-global `AtomicU16` counter resets independently and causes
/// collisions). The caller reads the actual address via `listener.local_addr()`
/// and passes the listener here; the config is used for all non-bind settings
/// (upstream URL, timeouts, etc.) but its `bind_addr` is ignored.
///
/// Production code always uses [`run_server`]; this variant is only compiled
/// when the `testing` feature is enabled.
///
/// # Errors
///
/// Returns [`ProxyError::TlsConfig`] if the upstream TLS client cannot be
/// initialised. The listener's local address is read for logging only.
#[cfg(any(test, feature = "testing"))]
pub async fn run_server_with_listener(
    listener: TcpListener,
    config: ProxyConfig,
    pipeline: TransformPipeline,
    analytics: Arc<dyn AnalyticsHook>,
) -> Result<(), ProxyError> {
    let addr = listener.local_addr().map_err(|e| ProxyError::BindFailed {
        addr: "pre-bound".to_string(),
        source: e,
    })?;
    let config = Arc::new(config);
    let pipeline = Arc::new(pipeline);
    let readiness = ReadinessState::new();
    let upstream_client =
        Arc::new(UpstreamClient::new().map_err(|e| ProxyError::TlsConfig(e.to_string()))?);

    info!(addr = %addr, "proxy listening (pre-bound)");

    serve_listener(
        listener,
        config,
        pipeline,
        analytics,
        upstream_client,
        readiness,
    )
    .await
}

// ============================================================================
// Signal handling
// ============================================================================

/// Wait for SIGINT (Ctrl-C) or SIGTERM (kill).
///
/// Returns when either signal is received. Used by the accept loop to trigger
/// graceful shutdown (AC23 / AD-PXY-14).
async fn wait_for_shutdown_signal() {
    #[cfg(unix)]
    {
        use tokio::signal::unix::{SignalKind, signal};
        // Registration failure is a fatal misconfiguration (e.g. signal already
        // blocked by a parent process). Return immediately so the caller can
        // trigger shutdown gracefully rather than hanging on a signal that never
        // fires. Production container environments always allow SIGINT/SIGTERM.
        let Ok(mut sigint) = signal(SignalKind::interrupt()) else {
            return;
        };
        let Ok(mut sigterm) = signal(SignalKind::terminate()) else {
            return;
        };
        tokio::select! {
            _ = sigint.recv() => {},
            _ = sigterm.recv() => {},
        }
    }
    #[cfg(not(unix))]
    {
        // Windows: only ctrl_c is available. Failure is non-fatal — return
        // immediately so the caller shuts down gracefully.
        let _ = tokio::signal::ctrl_c().await;
    }
}

// ============================================================================
// Tests (AC9, AC22, AC23)
// ============================================================================

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::detect::ProxyProvider;

    // AC13: request IDs are monotonically increasing and not derived from headers.
    #[test]
    fn test_request_id_monotonic() {
        let id1 = next_request_id();
        let id2 = next_request_id();
        assert!(
            id1.starts_with("px-"),
            "request ID must start with px-: {id1}"
        );
        assert!(
            id2.starts_with("px-"),
            "request ID must start with px-: {id2}"
        );
        assert_ne!(id1, id2, "request IDs must be unique");
    }

    // AC13: request ID format never looks like a header value.
    #[test]
    fn test_request_id_not_api_key_shaped() {
        for _ in 0..10 {
            let id = next_request_id();
            // Must not start with known API key prefixes.
            assert!(
                !id.starts_with("sk-ant-"),
                "request ID must not look like an API key: {id}"
            );
            assert!(
                !id.starts_with("Bearer "),
                "request ID must not look like a bearer token: {id}"
            );
        }
    }

    // AC22: json_response helper produces valid responses.
    #[test]
    fn test_json_response_helper() {
        let resp = json_response(StatusCode::OK, r#"{"status":"ok"}"#);
        assert_eq!(resp.status(), StatusCode::OK);
        // Content-type header present.
        let ct = resp
            .headers()
            .get(hyper::header::CONTENT_TYPE)
            .and_then(|v| v.to_str().ok())
            .unwrap_or("");
        assert!(ct.contains("application/json"), "must be application/json");
    }

    // AC9 marker: catch_unwind around analytics should not fail the request.
    // This test directly verifies the pattern used in handle_request.
    #[test]
    fn test_catch_unwind_analytics_panic_does_not_propagate() {
        struct PanicHook;
        impl AnalyticsHook for PanicHook {
            fn on_request(&self, _event: &ProxyEvent) {
                // Intentional panic to test containment.
                // In tests, panic is allowed.
                std::panic::catch_unwind(|| panic!("test panic")).ok();
            }
        }

        let hook = Arc::new(PanicHook);
        let event = ProxyEvent::new(
            ProxyProvider::Anthropic,
            None,
            None,
            crate::analytics::RequestTier::Passthrough,
            Bytes::new(),
            Bytes::new(),
            vec![],
            None,
            Duration::ZERO,
        );

        // This simulates the catch_unwind used in handle_request.
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            hook.on_request(&event);
        }));
        // Should not propagate — either Ok or caught.
        drop(result);
        // If we reach here, the test passes (no uncaught panic).
    }

    // ========================================================================
    // derive_tier unit tests (AD-PXY-21 / Cross-Plan Amendment #3)
    // ========================================================================

    /// AD-PXY-21: empty record set → Passthrough.
    #[test]
    fn test_derive_tier_empty_records_passthrough() {
        assert_eq!(derive_tier(&[]), RequestTier::Passthrough);
    }

    /// AD-PXY-21: one Full record from "block-router" → Full.
    #[test]
    fn test_derive_tier_block_router_full_returns_full() {
        let records = vec![DecisionRecord::modified("req-1", "block-router", 100, 80)];
        assert_eq!(derive_tier(&records), RequestTier::Full);
    }

    /// AD-PXY-21: one Degraded record from "block-router" → Degraded.
    #[test]
    fn test_derive_tier_block_router_degraded_returns_degraded() {
        let records = vec![DecisionRecord::modified_with_reason(
            "req-1",
            "block-router",
            100,
            90,
            OutcomeReason::Degraded,
        )];
        assert_eq!(derive_tier(&records), RequestTier::Degraded);
    }

    /// AD-PXY-21: Degraded trumps Full when both are present.
    #[test]
    fn test_derive_tier_degraded_trumps_full() {
        let records = vec![
            DecisionRecord::modified("req-1", "block-router", 100, 80), // Full
            DecisionRecord::modified_with_reason(
                "req-1",
                "block-router",
                80,
                80,
                OutcomeReason::Degraded,
            ),
        ];
        assert_eq!(derive_tier(&records), RequestTier::Degraded);
    }

    /// Cross-Plan Amendment #3: "cache-align" Full records are excluded.
    #[test]
    fn test_derive_tier_filters_non_block_router_components() {
        let records = vec![
            DecisionRecord::modified("req-1", "cache-align", 100, 80), // Full but wrong component
        ];
        // "cache-align" is not "block-router" — must remain Passthrough.
        assert_eq!(derive_tier(&records), RequestTier::Passthrough);
    }

    /// Cross-Plan Amendment #3: mixed components — only block-router records count.
    #[test]
    fn test_derive_tier_mixed_components_only_block_router_counts() {
        let records = vec![
            DecisionRecord::modified("req-1", "cache-align", 100, 80), // Full, excluded
            DecisionRecord::passthrough("req-1", "block-router", 80),   // Passthrough, included
        ];
        // Only the block-router Passthrough record counts — result: Passthrough.
        assert_eq!(derive_tier(&records), RequestTier::Passthrough);
    }

    // ========================================================================
    // project_decision unit tests (AD-AN-13 / AD-PXY-21)
    // ========================================================================

    /// AD-AN-13: project_decision maps Full → "full".
    #[test]
    fn test_project_decision_full_outcome() {
        let record = DecisionRecord::modified("req-1", "block-router", 200, 150);
        let proj = project_decision(&record);
        assert_eq!(proj.outcome, "full");
        assert_eq!(proj.component, "block-router");
        assert_eq!(proj.bytes_in, 200);
        assert_eq!(proj.bytes_out, 150);
    }

    /// AD-AN-13: project_decision maps Passthrough → "passthrough".
    #[test]
    fn test_project_decision_passthrough_outcome() {
        let record = DecisionRecord::passthrough("req-1", "block-router", 200);
        let proj = project_decision(&record);
        assert_eq!(proj.outcome, "passthrough");
        assert_eq!(proj.bytes_in, 200);
        assert_eq!(proj.bytes_out, 200); // passthrough preserves size
    }

    /// AD-AN-13: project_decision maps Degraded → "degraded".
    #[test]
    fn test_project_decision_degraded_outcome() {
        let record = DecisionRecord::modified_with_reason(
            "req-1",
            "block-router",
            200,
            190,
            OutcomeReason::Degraded,
        );
        let proj = project_decision(&record);
        assert_eq!(proj.outcome, "degraded");
    }
}
