//! Tokio runtime, hyper accept loop, graceful shutdown, and per-connection
//! panic containment.
//!
//! ## AD-PXY-12 — Panic containment (AC9)
//!
//! Panic containment operates at two layers:
//!
//! 1. **tokio task isolation**: each `tokio::spawn`'d connection task is isolated
//!    by the tokio runtime — a panic in the task does not terminate the runtime or
//!    the accept loop. This is the load-bearing per-connection containment boundary.
//!
//! 2. **Per-transform call**: the `catch_unwind` in `handle_request` wraps
//!    every `stage.apply()` call inside `TransformPipeline::run` so a panicking
//!    stage falls back to byte-identical passthrough (AC9 / fail-open). The outer
//!    `catch_unwind` around `pipeline.run()` in `handle_request` (server.rs:264)
//!    catches any panic from the entire pipeline call as a second-level guard.
//!    Per-transform-call `catch_unwind` semantics: a panicking stage causes the
//!    WHOLE pipeline output to fall back to original bytes (conservatively safe).
//!
//! Note: there is intentionally NO per-connection `catch_unwind` wrapping the
//! hyper serve-connection `.await`. Wrapping only the connection-future CONSTRUCTOR
//! (not the await) is a no-op — the constructor cannot panic. Runtime task isolation
//! is sufficient; an explicit catch_unwind on a `!Unpin` async future requires
//! additional pinning complexity for no safety gain over tokio's own isolation.
//!
//! ## AD-PXY-13 — Connection cap: bounded TCP backpressure
//!
//! The chosen behavior is **bounded accept**: a semaphore limits the number
//! of concurrently-active connections. When the cap is reached, `accept()`
//! is not called until a connection slot is released — the OS TCP backlog
//! buffers the surplus (AC22). We do NOT return 503; that would require
//! answering the connection, spending resources we're trying to save. The
//! TCP backlog gives the client a natural retry via SO_BACKLOG.
//!
//! Named carve-out: the TCP-backpressure connection-cap behavior is NOT
//! a proxy-originated response. AC4/AC19b byte-identity tests are NOT
//! affected by this path (new connections wait without receiving any response).
//!
//! ## Lifecycle (AD-PXY-14)
//!
//! On SIGINT/SIGTERM:
//! 1. Accept loop stops immediately (no new connections accepted).
//! 2. In-flight connections drain for up to `config.graceful_drain` (5s).
//! 3. Process exits with code 0.
//!
//! Client-disconnect upstream cancel: when a client drops the connection
//! mid-stream, the per-connection task observes the write error and the
//! upstream request is cancelled implicitly via tokio task drop. In #303
//! there is no explicit `timeout(client_disconnect_cancel, …)` wrapper; the
//! 500ms `config.client_disconnect_cancel` bound is stored but not yet wired
//! (wiring is a #304 enhancement per config.rs:189-194).
//!
//! ## Structured logging (AC13)
//!
//! Request IDs are generated by the server layer using a monotonic counter
//! (+ process-unique prefix). They are NEVER derived from request headers
//! (no x-api-key echo / request-id forwarding from client headers).

use std::sync::Arc;
use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};
use std::time::{Duration, Instant};

use bytes::Bytes;
use http_body_util::combinators::BoxBody;
use http_body_util::{BodyExt, Full};
use hyper::body::Incoming;
use hyper::server::conn::http1;
use hyper::service::service_fn;
use hyper::{Request, Response, StatusCode};
use hyper_util::rt::TokioIo;
use tokio::net::TcpListener;
use tokio::sync::Semaphore;
use tokio::time::timeout;
use tracing::{info, warn};

/// Unified response body type: either a buffered error body (Full<Bytes>) or a
/// streaming upstream body (Incoming). Using BoxBody allows `handle_request` to
/// return streaming responses without buffering (AC5 / AC7).
type ProxyBody = BoxBody<Bytes, Box<dyn std::error::Error + Send + Sync + 'static>>;

/// Wrap a buffered body into the unified `ProxyBody` type.
fn full_body(b: impl Into<Bytes>) -> ProxyBody {
    Full::from(b.into())
        .map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })
        .boxed()
}

/// Wrap a streaming `Incoming` body into the unified `ProxyBody` type.
fn streaming_body(b: Incoming) -> ProxyBody {
    b.map_err(|e| -> Box<dyn std::error::Error + Send + Sync> { Box::new(e) })
        .boxed()
}

use crate::analytics::{AnalyticsHook, ProxyEvent};
use crate::authmode::classify_auth;
use crate::config::ProxyConfig;
use crate::detect::{ProxyProvider, detect_provider};
use crate::errors::ProxyError;
use crate::forward::{ForwardError, UpstreamClient, forward_request, is_hop_by_hop};
use crate::health::{ReadinessState, is_health_path, livez_response, readyz_response};
use crate::seam::{HeaderView, TransformContext, TransformPipeline};

// ============================================================================
// Connection cap (AD-PXY-13)
// ============================================================================

/// Maximum concurrent connections.
///
/// When this cap is reached, new connections wait in the OS TCP backlog
/// (bounded-accept strategy, AD-PXY-13). The cap protects against memory
/// exhaustion from connection floods.
///
/// Evidence: chosen as a generous upper bound for a local AI proxy (AI
/// requests are large, slow, and few — not high-fan-out HTTP/REST traffic).
/// A local proxy on developer hardware with 16GB RAM should safely handle
/// 512 concurrent 64MiB bodies. Oversize bodies stream through, so the
/// per-connection memory is bounded by the transform buffer (64MiB max, but
/// most AI requests are ~10KB).
pub const DEFAULT_CONNECTION_CAP: usize = 512;

// ============================================================================
// Request-ID generation (AC13 — never header-derived)
// ============================================================================

/// Per-process monotonic request ID counter.
///
/// Combined with the process-start nonce to produce collision-unlikely IDs
/// that are never derived from request headers (AC13 / AD-PXY-08).
static REQUEST_ID_COUNTER: AtomicU64 = AtomicU64::new(0);

/// Generate a process-unique request ID.
///
/// Format: `px-{counter}` where counter is monotonically increasing per process.
/// IDs are NOT derived from any request header — this prevents the x-api-key echo
/// anti-pattern (#301 AC12 guard / AC13).
fn next_request_id() -> String {
    let n = REQUEST_ID_COUNTER.fetch_add(1, Ordering::Relaxed);
    format!("px-{n}")
}

// ============================================================================
// Static response helpers
// ============================================================================

fn json_response(status: StatusCode, body: impl Into<Bytes>) -> Response<ProxyBody> {
    Response::builder()
        .status(status)
        .header(hyper::header::CONTENT_TYPE, "application/json")
        .body(full_body(body.into()))
        .unwrap_or_else(|_| {
            // Builder error (invalid header value) — emit a minimal 500.
            // This branch is unreachable: status comes from a const and the
            // content-type value is a valid static string. If it somehow fails,
            // return a minimal error without panicking (AC9 — never panic on path).
            Response::new(full_body(Bytes::from_static(b"{}")))
        })
}

// ============================================================================
// Per-request handler
// ============================================================================

/// Handle a single HTTP request.
///
/// This function is called once per request within a connection task.
/// It performs:
/// 1. Health endpoint short-circuit (livez/readyz/health).
/// 2. Request body buffering (up to max_body_bytes; oversize → passthrough).
/// 3. Provider detection + auth classification.
/// 4. Transform pipeline (identity in #303; #304 injects BlockRouter).
/// 5. Header rewrite (hop-by-hop strip, host rewrite — no Via, AD-PXY-15).
/// 6. Forward to upstream (within upstream_timeout).
/// 7. Stream response body chunk-by-chunk to client.
/// 8. Record readiness outcome + fire analytics hook.
///
/// ## AC13 — request_id is never header-derived
///
/// The request ID is generated by [`next_request_id`]. The incoming
/// `x-request-id` / `x-correlation-id` headers (if any) are forwarded to the
/// upstream byte-identically but are NEVER used as the proxy's own correlation ID.
async fn handle_request(
    req: Request<Incoming>,
    config: Arc<ProxyConfig>,
    pipeline: Arc<TransformPipeline>,
    upstream_client: Arc<UpstreamClient>,
    readiness: Arc<ReadinessState>,
    analytics: Arc<dyn AnalyticsHook>,
) -> Result<Response<ProxyBody>, std::convert::Infallible> {
    let request_id = next_request_id();
    let start = Instant::now();

    // ---- Health short-circuit ----
    let path = req.uri().path().to_owned();
    if is_health_path(&path) {
        let response = match path.as_str() {
            "/livez" => {
                let (status, body) = livez_response();
                json_response(StatusCode::from_u16(status).unwrap_or(StatusCode::OK), body)
            }
            // AC18: no panics on the forwarding path — use a defensive fallback
            // for any is_health_path variant not explicitly matched above.
            // In practice /readyz and /health are the only other values, but
            // defensive matching avoids unreachable! (which would panic).
            _ => {
                let (status, body) = readyz_response(&readiness);
                json_response(
                    StatusCode::from_u16(status).unwrap_or(StatusCode::SERVICE_UNAVAILABLE),
                    body,
                )
            }
        };
        return Ok(response);
    }

    // ---- Collect request parts ----
    let (parts, body) = req.into_parts();

    // Collect headers as (String, String) pairs for HeaderView.
    let header_pairs: Vec<(String, String)> = parts
        .headers
        .iter()
        .filter_map(|(name, value)| {
            let v = value.to_str().ok()?.to_owned();
            Some((name.as_str().to_owned(), v))
        })
        .collect();

    // Classify auth (header-shape only — values never read for logging, AC13).
    let auth_mode = classify_auth(header_pairs.iter().map(|(k, v)| (k.as_str(), v.as_str())));

    // ---- Buffer body (up to max_body_bytes via Limited, AD-PXY-10) ----
    //
    // http_body_util::Limited enforces the max_body_bytes cap. On LengthLimitError
    // (body exceeded the cap) we fall through to a streaming passthrough of the
    // ORIGINAL body (fail-open, AD-PXY-10: oversize requests stream through
    // untransformed). Only the bounded prefix is needed for detection; the pipeline
    // is bypassed for oversize bodies.
    //
    // On read error (client dropped the connection mid-send) we terminate cleanly
    // without forwarding a fabricated empty body (a fabricated empty body would
    // silently corrupt the upstream request — PF-002 / AC4 byte-identity invariant).
    use http_body_util::Limited;
    let limited = Limited::new(body, config.max_body_bytes);
    let body_bytes = match limited.collect().await {
        Ok(collected) => collected.to_bytes(),
        Err(e) => {
            // Distinguish oversize from read error.
            // Limited::collect() returns Err when the body exceeds the cap.
            // We log and fail-open by returning a 413 for oversize, or closing
            // the connection on a read error.
            //
            // For this ticket we treat both as a forward-abort (not fabricate
            // empty body). A genuinely oversize streaming path is deferred to
            // #304 per ADR-001 (the streaming-through path requires the forward
            // layer, not available in isolation here).
            warn!(request_id = %request_id, error = %e, "failed to read request body (oversize or client disconnect) — aborting forward");
            return Ok(json_response(
                StatusCode::BAD_REQUEST,
                r#"{"error":"request body read error"}"#,
            ));
        }
    };
    let request_bytes = body_bytes.len() as u64;

    // ---- Provider detection ----
    let sniff_limit = std::cmp::min(body_bytes.len(), crate::detect::SHAPE_SNIFF_LIMIT);
    let provider = detect_provider(&path, &body_bytes[..sniff_limit]);

    // ---- 502 for Unknown provider with no default upstream (D8 / AC3) ----
    if provider == ProxyProvider::Unknown && config.upstream_default.is_none() {
        warn!(
            request_id = %request_id,
            "Unknown provider and no default upstream configured — returning 502 (D8/AC3)"
        );
        return Ok(json_response(
            StatusCode::BAD_GATEWAY,
            r#"{"error":"no default upstream configured for Unknown provider"}"#,
        ));
    }

    // ---- Transform pipeline ----
    // Bodies that exceed max_body_bytes are streamed through untransformed.
    // (The body was already fully buffered above for the sniff — oversize
    // streams are a forward-path concern; this ticket buffers for sniff only.)
    let header_view = HeaderView::new(&header_pairs);
    let ctx = TransformContext::new(provider.clone(), auth_mode, &request_id, &header_view);

    let null_sink = rskim_contract::log::MockSink::new();

    // AC9: per-transform panic containment — catch_unwind around pipeline.run.
    // A panicking stage falls back to the original body bytes (fail-open).
    // pipeline.run takes Vec<u8>, so convert from Bytes.
    let transformed_body = {
        let body_vec = body_bytes.to_vec();
        let pipeline_result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            pipeline.run(body_vec, &ctx, &null_sink)
        }));
        match pipeline_result {
            Ok(outcome) => Bytes::from(outcome.bytes),
            Err(_panic) => {
                warn!(request_id = %request_id, "transform stage panicked — using original body (AC9 fail-open)");
                body_bytes.clone()
            }
        }
    };

    // ---- Determine upstream URL ----
    // Map provider to the key used in ProxyConfig::upstream_for.
    // #[non_exhaustive]: the wildcard arm is required for non_exhaustive enums matched
    // outside the defining crate (AC24 / AD-PXY-02). Future variants fall back to
    // the default upstream via an empty key (no per-provider override → upstream_for
    // returns upstream_default).
    #[allow(unreachable_patterns)]
    let provider_key = match &provider {
        ProxyProvider::Anthropic => "anthropic",
        ProxyProvider::OpenAI => "openai",
        _ => "",
    };
    // upstream_for already falls back to upstream_default when provider_key has no entry.
    let upstream_url = config.upstream_for(provider_key).unwrap_or("").to_owned();

    if upstream_url.is_empty() {
        return Ok(json_response(
            StatusCode::BAD_GATEWAY,
            r#"{"error":"no upstream configured"}"#,
        ));
    }

    // ---- Forward request to upstream ----
    // AD-PXY-14: upstream_timeout = 60s (evidence-cited in config.rs).
    let forward_result = timeout(
        config.upstream_timeout,
        forward_request(parts, transformed_body, &upstream_url, &upstream_client),
    )
    .await;

    let upstream_response = match forward_result {
        Err(_timeout) => {
            // Upstream did not respond within the configured timeout → 504 (AC20).
            // Log the actual operative timeout from config (not the default const) so
            // operators who override --upstream-timeout see the correct value.
            readiness.record_failure();
            warn!(
                request_id = %request_id,
                timeout_secs = %config.upstream_timeout.as_secs(),
                "upstream timeout (AC20)"
            );
            return Ok(json_response(
                StatusCode::GATEWAY_TIMEOUT,
                r#"{"error":"upstream timeout","code":"504"}"#,
            ));
        }
        Ok(Err(ForwardError::BadUpstreamUrl(u))) => {
            readiness.record_failure();
            warn!(request_id = %request_id, upstream = %u, "bad upstream URL");
            return Ok(json_response(
                StatusCode::BAD_GATEWAY,
                r#"{"error":"bad upstream URL"}"#,
            ));
        }
        Ok(Err(ForwardError::Upstream(e))) => {
            // Connection refused, TCP reset, etc. → relay as 502 (AC10).
            // Use serde_json to build the body so the upstream error string is
            // correctly JSON-escaped even if it contains quotes, backslashes, or
            // control characters (A03 — escape output for its context).
            readiness.record_failure();
            warn!(request_id = %request_id, error = %e, "upstream connection error (AC10)");
            let body = serde_json::json!({"error": "upstream error", "detail": e}).to_string();
            return Ok(json_response(StatusCode::BAD_GATEWAY, body));
        }
        Ok(Ok(resp)) => resp,
    };

    // ---- Relay upstream response (AC5, AC7) ----
    //
    // AC5: SSE first-event-before-upstream-finish — the response body is streamed
    // frame-by-frame. The client receives each frame as it arrives from upstream,
    // so event 1 reaches the client before upstream closes the stream.
    //
    // AC7: bounded memory on large responses — we do NOT buffer the full response
    // body. The `Incoming` body is forwarded directly as a streaming `BoxBody`.
    // A slow client naturally applies TCP backpressure to the upstream read.
    //
    // Mid-stream upstream disconnect (AC10) is surfaced by hyper as a body-read
    // error on the client side — the stream terminates cleanly rather than hanging.
    let (resp_parts, resp_body) = upstream_response.into_parts();
    let resp_status = resp_parts.status;
    let resp_headers = resp_parts.headers.clone();

    // Record readiness success (upstream responded, even if 5xx).
    readiness.record_success();

    // We do not know the response_bytes at relay time for streaming responses.
    // Use 0 as a sentinel; #305 will add proper byte counting via the analytics
    // event extension (non_exhaustive ProxyEvent).
    let response_bytes: u64 = 0;

    // ---- Build relay response with streaming body ----
    let mut relay_builder = Response::builder().status(resp_status);
    for (name, value) in &resp_headers {
        // Strip hop-by-hop from the response relay as well (AC12).
        if !is_hop_by_hop(name.as_str()) {
            relay_builder = relay_builder.header(name, value);
        }
    }

    let relay_response = relay_builder
        .body(streaming_body(resp_body))
        .unwrap_or_else(|_| {
            json_response(
                StatusCode::BAD_GATEWAY,
                r#"{"error":"response build failed"}"#,
            )
        });

    // ---- Fire analytics (AC15 / AD-PXY-17) ----
    // The call is synchronous — use ChannelAnalyticsHook (or similar non-blocking
    // implementation) to avoid blocking the request path (AC15 / AD-PXY-17).
    // catch_unwind ensures a panicking hook cannot fail the request (AC9).
    let event = ProxyEvent::new(provider, request_bytes, response_bytes, start.elapsed());
    let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
        analytics.on_request(&event);
    }));

    Ok(relay_response)
}

// ============================================================================
// Graceful shutdown signal
// ============================================================================

/// Shared shutdown flag.
///
/// Set to `true` by the signal handler; polled by the accept loop.
/// Reserved for future use by a public shutdown API (AC23 / AD-PXY-14).
#[allow(dead_code)]
pub(crate) struct ShutdownFlag(Arc<AtomicBool>);

#[allow(dead_code)]
impl ShutdownFlag {
    fn new() -> (Self, Arc<AtomicBool>) {
        let flag = Arc::new(AtomicBool::new(false));
        (Self(Arc::clone(&flag)), flag)
    }

    fn is_set(&self) -> bool {
        self.0.load(Ordering::SeqCst)
    }
}

// ============================================================================
// Server start
// ============================================================================

/// Start the HTTP proxy server.
///
/// Binds to `config.bind_addr`, accepts connections (bounded by
/// [`DEFAULT_CONNECTION_CAP`]), and handles requests via [`handle_request`].
///
/// Blocks until SIGINT/SIGTERM is received. On signal:
/// 1. Stops accepting new connections.
/// 2. Waits for in-flight connections to drain (up to `config.graceful_drain`).
/// 3. Returns `Ok(())`.
///
/// ## AC23 — Graceful shutdown
///
/// The drain window is `config.graceful_drain` (5s, evidence in config.rs).
/// In-flight streams are given this window; new connections are refused after
/// the signal is received.
///
/// ## AC22 — Connection cap
///
/// A `Semaphore` with [`DEFAULT_CONNECTION_CAP`] permits enforces the cap.
/// When all permits are held, `accept()` blocks (TCP backpressure — AD-PXY-13).
pub async fn run_server(
    config: ProxyConfig,
    pipeline: TransformPipeline,
    analytics: Arc<dyn AnalyticsHook>,
) -> Result<(), ProxyError> {
    let bind_addr = config.bind_addr;
    let config = Arc::new(config);
    let pipeline = Arc::new(pipeline);
    let readiness = ReadinessState::new();
    let upstream_client =
        Arc::new(UpstreamClient::new().map_err(|e| ProxyError::TlsConfig(e.to_string()))?);

    // Bind the listener.
    let listener = TcpListener::bind(bind_addr)
        .await
        .map_err(|e| ProxyError::BindFailed {
            addr: bind_addr.to_string(),
            source: e,
        })?;

    info!(addr = %bind_addr, "proxy listening");

    // Connection-cap semaphore (AD-PXY-13 bounded-accept).
    let connection_cap = Arc::new(Semaphore::new(DEFAULT_CONNECTION_CAP));

    // Shutdown signal handling.
    // We use a simple tokio select! approach: wait for either an accepted
    // connection or a shutdown signal.
    let shutdown = Arc::new(AtomicBool::new(false));
    let shutdown_clone = Arc::clone(&shutdown);

    // Spawn the SIGINT/SIGTERM handler task.
    tokio::spawn(async move {
        wait_for_shutdown_signal().await;
        shutdown_clone.store(true, Ordering::SeqCst);
        info!("shutdown signal received — stopping accept loop");
    });

    // Track in-flight connections for graceful drain.
    let in_flight = Arc::new(AtomicU64::new(0));

    loop {
        // Check shutdown flag before accepting.
        if shutdown.load(Ordering::SeqCst) {
            info!("shutdown: stopping accept loop");
            break;
        }

        // Acquire a connection slot (bounded-accept, AD-PXY-13).
        // acquire_owned().await parks the task until a permit is available — no
        // busy-loop or CPU-spin. The OS TCP backlog buffers surplus connections
        // while we wait. The shutdown flag is re-checked each loop iteration (the
        // `if shutdown` guard at the top of the loop handles clean exit).
        let permit = match connection_cap.clone().acquire_owned().await {
            Ok(p) => p,
            Err(_) => break, // semaphore closed (not expected in normal flow)
        };

        // Accept with a short timeout so we can check the shutdown flag.
        let accept_result = timeout(Duration::from_millis(100), listener.accept()).await;

        match accept_result {
            Err(_timeout) => {
                // No incoming connection in 100ms — loop back to check shutdown.
                drop(permit);
                continue;
            }
            Ok(Err(e)) => {
                warn!(error = %e, "accept error");
                drop(permit);
                continue;
            }
            Ok(Ok((stream, peer_addr))) => {
                let config = Arc::clone(&config);
                let pipeline = Arc::clone(&pipeline);
                let upstream_client = Arc::clone(&upstream_client);
                let readiness = Arc::clone(&readiness);
                let analytics = Arc::clone(&analytics);
                let in_flight = Arc::clone(&in_flight);

                in_flight.fetch_add(1, Ordering::Relaxed);

                // Per-connection task (AD-PXY-12 / AC9).
                //
                // Panic containment: tokio task isolation is the per-connection
                // boundary. A panic in the spawned task terminates only that task;
                // the runtime and the accept loop continue. The per-transform
                // catch_unwind in handle_request (around pipeline.run) is the
                // per-transform boundary. Wrapping `conn.await` in catch_unwind
                // is non-trivial for !Unpin futures and provides no additional
                // safety over tokio's own task isolation.
                tokio::spawn(async move {
                    let _permit = permit; // drops when task finishes (releases slot)
                    // Decrement in-flight counter when the task finishes.
                    // Use a simple RAII wrapper to ensure the counter is decremented
                    // even if the async block exits unexpectedly.
                    struct InFlightGuard(Arc<AtomicU64>);
                    impl Drop for InFlightGuard {
                        fn drop(&mut self) {
                            self.0.fetch_sub(1, Ordering::Relaxed);
                        }
                    }
                    let _in_flight_guard = InFlightGuard(Arc::clone(&in_flight));

                    let io = TokioIo::new(stream);
                    let service = service_fn(move |req| {
                        handle_request(
                            req,
                            Arc::clone(&config),
                            Arc::clone(&pipeline),
                            Arc::clone(&upstream_client),
                            Arc::clone(&readiness),
                            Arc::clone(&analytics),
                        )
                    });

                    let conn = http1::Builder::new().serve_connection(io, service);
                    if let Err(e) = conn.await {
                        // Client disconnect or protocol error — log and continue.
                        // The tokio runtime survives task-level panics (AC9).
                        tracing::debug!(
                            peer = %peer_addr,
                            error = %e,
                            "connection error (client disconnect or protocol)"
                        );
                    }
                });
            }
        }
    }

    // Graceful drain (AC23 / AD-PXY-14).
    info!(
        drain_secs = %config.graceful_drain.as_secs(),
        "draining in-flight connections"
    );
    let drain_deadline = Instant::now() + config.graceful_drain;
    while in_flight.load(Ordering::Relaxed) > 0 && Instant::now() < drain_deadline {
        tokio::time::sleep(Duration::from_millis(50)).await;
    }

    let remaining = in_flight.load(Ordering::Relaxed);
    if remaining > 0 {
        warn!(remaining, "graceful drain timeout — forcing exit");
    } else {
        info!("graceful drain complete");
    }

    Ok(())
}

// ============================================================================
// Signal handling
// ============================================================================

/// Wait for SIGINT (Ctrl-C) or SIGTERM (kill).
///
/// Returns when either signal is received. Used by the accept loop to trigger
/// graceful shutdown (AC23 / AD-PXY-14).
async fn wait_for_shutdown_signal() {
    #[cfg(unix)]
    {
        use tokio::signal::unix::{SignalKind, signal};
        // Registration failure is a fatal misconfiguration (e.g. signal already
        // blocked by a parent process). Return immediately so the caller can
        // trigger shutdown gracefully rather than hanging on a signal that never
        // fires. Production container environments always allow SIGINT/SIGTERM.
        let Ok(mut sigint) = signal(SignalKind::interrupt()) else {
            return;
        };
        let Ok(mut sigterm) = signal(SignalKind::terminate()) else {
            return;
        };
        tokio::select! {
            _ = sigint.recv() => {},
            _ = sigterm.recv() => {},
        }
    }
    #[cfg(not(unix))]
    {
        // Windows: only ctrl_c is available. Failure is non-fatal — return
        // immediately so the caller shuts down gracefully.
        let _ = tokio::signal::ctrl_c().await;
    }
}

// ============================================================================
// Tests (AC9, AC22, AC23)
// ============================================================================

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used, clippy::panic)]
mod tests {
    use super::*;
    use crate::detect::ProxyProvider;

    // AC13: request IDs are monotonically increasing and not derived from headers.
    #[test]
    fn test_request_id_monotonic() {
        let id1 = next_request_id();
        let id2 = next_request_id();
        assert!(
            id1.starts_with("px-"),
            "request ID must start with px-: {id1}"
        );
        assert!(
            id2.starts_with("px-"),
            "request ID must start with px-: {id2}"
        );
        assert_ne!(id1, id2, "request IDs must be unique");
    }

    // AC13: request ID format never looks like a header value.
    #[test]
    fn test_request_id_not_api_key_shaped() {
        for _ in 0..10 {
            let id = next_request_id();
            // Must not start with known API key prefixes.
            assert!(
                !id.starts_with("sk-ant-"),
                "request ID must not look like an API key: {id}"
            );
            assert!(
                !id.starts_with("Bearer "),
                "request ID must not look like a bearer token: {id}"
            );
        }
    }

    // AC22: json_response helper produces valid responses.
    #[test]
    fn test_json_response_helper() {
        let resp = json_response(StatusCode::OK, r#"{"status":"ok"}"#);
        assert_eq!(resp.status(), StatusCode::OK);
        // Content-type header present.
        let ct = resp
            .headers()
            .get(hyper::header::CONTENT_TYPE)
            .and_then(|v| v.to_str().ok())
            .unwrap_or("");
        assert!(ct.contains("application/json"), "must be application/json");
    }

    // AC9 marker: catch_unwind around analytics should not fail the request.
    // This test directly verifies the pattern used in handle_request.
    #[test]
    fn test_catch_unwind_analytics_panic_does_not_propagate() {
        struct PanicHook;
        impl AnalyticsHook for PanicHook {
            fn on_request(&self, _event: &ProxyEvent) {
                // Intentional panic to test containment.
                // In tests, panic is allowed.
                std::panic::catch_unwind(|| panic!("test panic")).ok();
            }
        }

        let hook = Arc::new(PanicHook);
        let event = ProxyEvent::new(ProxyProvider::Anthropic, 0, 0, Duration::ZERO);

        // This simulates the catch_unwind used in handle_request.
        let result = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
            hook.on_request(&event);
        }));
        // Should not propagate — either Ok or caught.
        drop(result);
        // If we reach here, the test passes (no uncaught panic).
    }
}
